### ISSUE TITLE
Remove python3.3 support?

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/atramhasis#108]
Is support for python 3.3 still needed?

**Comment by koenedaele** [comment]
We could drop 3.3 when python 3.5 comes out. That should be around september 2015.

**Comment by koenedaele** [comment]
Seems  like python 3.5 has been released.

@BartSaelen Do we drop support for 3.3 now (0.5.0) or do we do this with the next release (0.6.0)?

**Comment by koenedaele** [comment]
I'm going to keep python 3.3 support around for version 0.5.0. Will be dropped in Atramhasis 0.6.0

**Comment by koenedaele** [comment]
Seems like we dropped it already. So closing this one.
