### ISSUE TITLE
Detailed export to RDF

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#126]
Currently, we have a way of exporting an entire scheme to rdf serialised as `rdf` (rdf/xml) or `ttl` (N3/Turtle).

We should also offer a detailed view of a certain concept or collection as rdf. Again, serialising to rdf/xml and N3/Turtle seems to cover a good number of cases.

So, when I hit the URI `http://localhost:6543/conceptschemes/STYLES/c/29` with a mime-type of `application/rdf+xml`, I should receive this concepts serialised as `application/rdf+xml`. For convenience and linkability, this should also work at `http://localhost:6543/conceptschemes/STYLES/c/29.rdf`. Same thing for `application/x-turtle` and the extension `.ttl`.

/cc @dieuska Please tackle this together with @BartSaelen

**Comment by dieuska** [comment]
@BartSaelen 
I already added  a method 'rdf_conceptscheme_dumper' to 'skosprovider_rdf' & added paths for 'export to rdf for conceptschem and individuals' in atramhasis + tests (RdfFunctionalTests). 

The hyperlinks to these paths for exporting to rdf are not yet included in the atramhasis front-end

**Comment by koenedaele** [comment]
I've added a few issues to skosprovider_rdf. Please look at these first.

**Comment by koenedaele** [comment]
I think the export is currently working for `http://localhost:6543/conceptschemes/STYLES/c/29.rdf`, but not for `http://localhost:6543/conceptschemes/STYLES/c/29` when requested with mime-type `application/rdf+xml`?

**Comment by koenedaele** [comment]
Also, please make the download file names more descriptive than skos.ttl and skos.xml (shoudl be skos.rdf I think). Suggestion, always make it into the identifier of the concept or collection. (eg. `15.rdf` or `15.ttl`)

For the conceptscheme, this would be `STYLES.rdf` or `STYLES.ttl`.

For the export of the full conceptscheme, this should be `STYLES-full.rdf` or `STYLES-full.ttl`.

**Comment by BartSaelen** [comment]
changed route config to support both 'text/turtle' and 'application/x-turtle' as per http://www.w3.org/TeamSubmission/turtle/#sec-mime
