### ISSUE TITLE
Right click menu extensions

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#137]
When using the right click menu, we can currently select "Add narrower" for a concept and "Add member of" for a collection.

This should be for a concept:

* Add narrower concept (open an edit screen for a concept with a Broader relation already defined)
* Add subordinate array (open an edit screen for a collection with a superordinate concept already defined)

For a collection:

* Add member (without the of) (open an edit screen for a concept with a Member Of relation already defined)

**Comment by cedrikv** [comment]
fixed in #160
