### ISSUE TITLE
Merging matches

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#144]
Currently, we can import a Concept or Collection from another scheme, but we can not update a record after it's been imported. Suppose we import a Concept. And a year later the provider we imported from has added 5 new labels and 2 new notes. If we wanted to have those on our side as well, we currently would need to re-import the record and destroy the current one or add everything manually.

What could work:
 * Adding a button *Merge* to concepts that have a skos:Match.
 * Open a dialog that allows you to select which (or all) of the existing matches you would like to merge with (ie. we might have a concept that matches with bot an AAT and an EH concept).
 * For each selected external provider, import all labels and notes, using the following rules:
  * If a label or note already exists with the same type, language and the same value, don't import.
  * If we are trying to import a prefLabel, and there is already a prefLabel for that language (but it's not the same prefLabel as the one we're trying to import), import the prefLabel as an altLabel .

**Comment by cedrikv** [comment]
fixed in #174
