### ISSUE TITLE
Importing a collection

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#145]
When importing a collection, an attempt seems to be made to create a match with this collection. But, skos:matches can only be created between skos:Concepts. So, when importing a collection, no match can be created.

For example, I can search the AAT provider for "form" and I get a bunch of collections back. If I import one, eg. "aat:300232663", I get the add concept dialog. There is no match visible. But when I press save,  I do get an error message saying that only Concepts can have matches.

On a possible unrelated note, I can't see any labels for AAT collections in some places, but they are there when I try to edit them. Is this because they are enclosed in "<" and ">" signs? Are we treating these as HTML in some places?

**Comment by BartSaelen** [comment]
labels are stored correctly, but I think "<" and ">" signs, are indeed interpreted as HTML

**Comment by koenedaele** [comment]
I think we need to pull the labels through dojo.string.escape. Actually, I think we need to pull just about any output that should not contain HTML through that function. Otherwise, we're very much at risk from XSS attacks and such,
