### ISSUE TITLE
language_id field too short

### ISSUE THREAD

**Issue by BartSaelen** [OnroerendErfgoed/atramhasis#147]
language_id field in note and label too short to match changes from #99

**Comment by BartSaelen** [comment]
ERROR [atramhasis.views.exception_views][Dummy-1] (DataError) value too long for type character varying(10)

**Comment by koenedaele** [comment]
Do we need to fix this upstream in skosprovider_sqlalchemy as well? If so, can you make a PR?

**Comment by BartSaelen** [comment]
indeed this needs to be fixed in skosprovider_sqlalchemy as well

**Comment by BartSaelen** [comment]
see https://github.com/koenedaele/skosprovider_sqlalchemy/pull/11
