### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#148]
I've noticed that startuptime of the app seems to be quite long nowadays. Eg, when starting I get:

```
(atramhasis)koen@Kador-proBook:~/Projecten/python/atramhasis$ pserve --reload development.ini 
Starting subprocess with file monitor
2015-01-28 15:38:56,722 INFO  [rdflib][MainThread] RDFLib Version: 4.1.2
2015-01-28 15:39:15,811 INFO  [sqlalchemy.engine.base.Engine][MainThread] SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
```

```
(atramhasis)koen@Kador-proBook:~/Projecten/python/atramhasis$ pserve --reload development.ini 
Starting subprocess with file monitor
2015-01-28 15:43:24,085 INFO  [rdflib][MainThread] RDFLib Version: 4.1.2
2015-01-28 15:45:08,224 INFO  [sqlalchemy.engine.base.Engine][MainThread] SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
```

Seems like it can take from 20 seconds to a minute and a half before SQLAlchemy starts connecting to the database.  Do we have any idea why it takes so long and why there's so much variation? This is on my machine (Ubuntu 12.04, python 2.7). I'm assuming it's got something to do with either skosprovider_rdf, skosprovider_getty or skosprovider_heritagedata.

**Comment by BartSaelen** [comment]
After further investigation, the delay seems to come from initializing the external providers (e.g. Getty, English Heritage)

**Comment by BartSaelen** [comment]
---Getty-> 6888 ms
---English Heritage-> 1290 ms

**Comment by koenedaele** [comment]
That's more or less what I was assuming. Any idea how exactly it happens? Are we querying something prematurely or handling the registry wrong?

**Comment by BartSaelen** [comment]
Both providers already connect to their external services during initialization phase. These connection might be slow. Also they already fetch some metadata during this phase. This is to pre-optimize and have better performance during querying.
In my opinion this is not a big deal as this is during start-up and only executed once. It wont influence overall performance of the application.

**Comment by koenedaele** [comment]
Ok. It doesn't seem to impact the app any further. Just wanted to make sure we weren't missing anything.

@dieuska could you perhaps add something to the skosprovider_getty docs that startup of the provider can take a while. I've got the impression skosprovider_getty has more issues because it's getting all the RDF subclass defintions? And skosprovider_hertitagedata does not doe that?

**Comment by dieuska** [comment]
Getty indeed checks indeed on intitialisation for all classes in the getty-ontology if they are a subclass of SKOS.Concept/SKOS.Collection. This as based on rdf so on initialisation a lot of requests happen.
This is not the case in hetitagedata.
