### ISSUE TITLE
Deploy a demo on Heroku

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#152]
I think it should be possible to run a demo of Atramhasis on Heroku. It probably won't be the most performant version on the free pricing tier, but I think we should be able to get it to work.

It would be nice to:
 1. Have a demo on Heroku
 2. Document for users how they can install an Atramhasis instance on Heroku

@BartSaelen Is this something you can explore? And let @dieuska help with writing out how it works?

**Comment by koenedaele** [comment]
Docs on deploying Pyramid apps on Heroku: http://pyramid-cookbook.readthedocs.org/en/latest/deployment/heroku.html

**Comment by BartSaelen** [comment]
Is there already an Heroku account for this?

**Comment by koenedaele** [comment]
No, I just created a personal test account yesterday evening for learning how Heroku works. 

But maybe we do need a general account for this. @maarten-vermeyen your thoughts?

**Comment by maarten-vermeyen** [comment]
I would prefer a general account for this as well.  If the free account is enough to host the demo app we'll go with heroku. If not we'll have to look into hosting a demo site on infrastructure of Onroerend Erfgoed or with a cloudprovider that sends actual invoices.

**Comment by koenedaele** [comment]
I think the free version should work for now. Further down the line we might want to set up our own server for it, or move to Amazon or whatever. I'm not sure how many cloud providers actually work with invoices since that's probably a lot harder to handle when you're dealing with up-down scaling of apps?

There's such a thing as a company account apparenty: https://devcenter.heroku.com/categories/organization-accounts. But I think it automatically needs a purchase.

Can we just create an atramhasis@onroerenderfgoed.be account and use that one?

Also, I just found this: https://devcenter.heroku.com/articles/heroku-button Seems like a cool thing to promote software and help people to quickly get something running?

**Comment by BartSaelen** [comment]
Manual for Heroku deployment now available at http://atramhasis.readthedocs.org/en/latest/demo.html#running-a-demo-site-on-heroku

**Comment by koenedaele** [comment]
Waiting for an Atramhasis Heroku account and then this can be fixed as well.

**Comment by koenedaele** [comment]
For the 0.4.1 release we'll go with the demo running on @BartSaelen's account.
