### ISSUE TITLE
Are we still using dojox?

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#154]
According to the bower.json for the admin interface, we're still using dojox. Is that actually still so? Or can we get rid of it?

**Comment by cedrikv** [comment]
dojox is still used for:
-form mixins
-validation
-layouting

**Comment by koenedaele** [comment]
So, not something we can get rid of that easily.

**Comment by cedrikv** [comment]
We will try to remove all the dojox stuff when we do the refactoring for the new style.

**Comment by taeymma** [comment]
dojox stuff isn't used anymore after refactor. Removed from bower.
