### ISSUE TITLE
What's up with zope_sqlalchemy?

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#162]
When upgrading this dependency to 0.7.5, two unit tests broke. Shouldn't happen for a minor update. Is it a problem on our or their side?

**Comment by BartSaelen** [comment]
I got this error:

    DetachedInstanceError: Instance <Collection at 0x7f1d09888f10> is not bound to a Session; attribute    refresh operation cannot proceed

problem seems to occur when using cached objects

**Comment by BartSaelen** [comment]
I think we are doing our caching in an incorrect way. Which leads to calling attributes on detached instances. This worked in the past, because of a bug in zope_sqlalchemy. This bug was fixed in 0.7.5.

I'll improve the caching and upgrade to zope_sqlalchemy 0.7.5 and dogpile.cache 0.5.6
