### ISSUE TITLE
Link from public frontend to admin

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#178]
It would be nice to be able to have a direct link from the public interface to the admin interface for users that have that permission. So, I could be looking at concept 15 in scheme X. If i'm logged in, I see a button that takes me straight to the admin interface for that concept.

@kmillet Something to think about with the redesign as well?

**Comment by taeymma** [comment]
Voorzien in frontend, routes moeten nog aangemaakt worden in beheerkant.

**Comment by cedrikv** [comment]
What format will we use for the routes? 
http://www.atramhasis.com/admin/#/<scheme id>/<concept-collection id> ?

**Comment by koenedaele** [comment]
I would mirror the frontend routes, so http://thesaurus.onroerenderfgoed.be/conceptschemes/Stijlen%20en%20culturen becomes http://thesaurus.onroerenderfgoed.be/admin/#/conceptschemes/Stijlen%20en%20culturen and http://thesaurus.onroerenderfgoed.be/conceptschemes/Stijlen%20en%20culturen/c/106 becomes http://thesaurus.onroerenderfgoed.be/admin/#/conceptschemes/Stijlen%20en%20culturen/c/106
