### ISSUE TITLE
JS Builds are erroring a lot

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#183]
Figure out if we can split the repo or something else? So we can have a travis js build and a travis python build? Might be fairly simple with something like git submodules?

**Comment by cedrikv** [comment]
Grunt build removed by @BartSaelen for now:
https://github.com/OnroerendErfgoed/atramhasis/commit/ea2da6e424275e30204c0086cc8b3cee9384cc06

**Comment by cedrikv** [comment]
no more problems with new setup
