### ISSUE TITLE
Make it shine

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#184]
Rework the default public interface into something that looks really good.

**Comment by koenedaele** [comment]
Designs have been made but @TOM-VC. Handing this over to @taeymma for implementation.

**Comment by koenedaele** [comment]
New style can be found in https://github.com/OnroerendErfgoed/atramhasisstijl

**Comment by koenedaele** [comment]
pseudocode to get to the object behind a match uri:

If you don't know what provider the URI is from:
```python
skosregistry.get_by_uri(match_uri)
```

If you know what provider the URI is from:
```python
skosregistry.get_provider('AAT').get_by_uri(match_uri)
```

**Comment by koenedaele** [comment]
Well, the pseudocode turns out to be actual code once you've got the skosregistry...

**Comment by taeymma** [comment]
als ik onderstaande code uitvoer krijg ik een boolean terug van get_by_uri..

provider = self.request.skos_registry.get_provider(scheme_id)
for match in c.matches:
                test = provider.get_by_uri(match.uri)

**Comment by taeymma** [comment]
Ok nm.. 
match has a concept field :)

**Comment by koenedaele** [comment]
I think that code should have been:

```python
provider = self.request.skos_registry.get_provider(scheme_id)
for matchtype in c.matches:
    for match in c.matches[matchtype]:
        test = provider.get_by_uri(match.uri)
```

Think I need to update the API docs for matches a bit.

**Comment by taeymma** [comment]
http://localhost:6543/conceptschemes/HERITAGETYPE/displaytop
http://localhost:6543/conceptschemes/HERITAGETYPE/c/<id>/displaychildren

**Comment by taeymma** [comment]
issue for new tree #233
