### ISSUE TITLE
Refactor routes

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#186]
Our includeme function in __init__.py already contains quite a lot of routes. Might be a good idea to move them to a routes.py file or so.

**Comment by koenedaele** [comment]
@BartSaelen Feedback? Do we do something like this in other projects?

If so, @TalissaJoly can take care of this.

**Comment by BartSaelen** [comment]
I think this is pretty straight forward. Just move route config to a routes.py and include it in init.

Not sure if we need this in other projects atm.

**Comment by koenedaele** [comment]
Ok, over to @TalissaJoly
