### ISSUE TITLE
Document services

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#187]
We've got a few services that are not showing up in our service docs, mainly dealing with languages, but also labeltypes and notetypes (although those last two are of minor importance).

We could also document the RDF downloads as service urls.

One problem here is that we're still referring to the pyramid_skosprovider docs for the read services. But, the distinction between read and write might no longer make sense.

**Comment by TalissaJoly** [comment]
So should i copy the service docs from pyramid_skosprovider? And create one long list with all services(read and write)?

**Comment by koenedaele** [comment]
The basic problem is that a big part of our service documentation is in pyramid_skosprovider.

We can deal with this in several ways:

* Leave it as it is. With most of the read services in pyramid_skosprovider and the rest in Atramhasis. Problem: you need to consult the docs of two projects to get all services.
* Copy the pyramid_skosprovider docs to Atramhasis. Problem: then we need to maintain and sync the same information in two docs.
* Find some way to inline the external documentation during PDF generation. So, that the current link to the pyramid_skosprovider docs becomes a local version.
* Do something like the previous thing, but script it ourselves? So, that we have a small task that fetches the pyramid_skosprovider docs and copies the relevant pieces to the Atramhasis docs. We could run this before every build of the docs or every time we package the app?

Further idea are welcome.
