### ISSUE TITLE
License for fixtures

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#192]
We have two sets of fixture data: https://github.com/OnroerendErfgoed/atramhasis/blob/master/fixtures/styles_and_cultures.py and https://github.com/OnroerendErfgoed/atramhasis/blob/master/fixtures/materials.py

These were generated a while ago from two of our current thesauri: https://inventaris.onroerenderfgoed.be/thesaurus/stijl and https://inventaris.onroerenderfgoed.be/thesaurus/materiaal.

The other 2 fixtures (in https://github.com/OnroerendErfgoed/atramhasis/blob/master/fixtures/data.py) I more or less created from scratch.

Since we're distributing these vocabularies with Atramhasis, do we need to add some kind of open data license for them?

**Comment by koenedaele** [comment]
@maarten-vermeyen Seems like something for you. I've put this on the 0.5.0 milestone because I don't think it's very urgent. On the other hand, it might also not be a lot of work. So, if you'd rather do this quickly, I can add it to 0.4.1 as well.

**Comment by koenedaele** [comment]
BTW, the `materials` and `styles and cultures` fixtures will be updated before the release of 0.4.1. See #191 But I don't think that changes anything.

**Comment by maarten-vermeyen** [comment]
I would use a dual licencing policy.

* CC attribution
* Vlaamse open data licentie: bronvermelding

**Comment by maarten-vermeyen** [comment]
I would use a dual licencing policy.

* CC attribution
* Vlaamse open data licentie: bronvermelding

**Comment by koenedaele** [comment]
Where would you add that? In the LICENSE file in the root folder, or should we keep that one for the software? Or add a LICENSE file to https://github.com/OnroerendErfgoed/atramhasis/tree/master/fixtures?

**Comment by maarten-vermeyen** [comment]
www.opendataforum.info/files/modellicenties_NL_28_03.pdf

Licentie 2: Gratis Open Data licentie
