### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#193]
Todo:

- [x] Update version numbers
- [x] Release and freeze dependencies
- [x] Test deploy of demo on Heroku

Target date: 04/03/2015

/cc @BartSaelen @dieuska

**Comment by koenedaele** [comment]
Most skosprovider dependencies have been frozen. Waiting on releases of OnroerendOrfgoed/language-tags and OnroerendErfgoed/skosprovider_rdf.

**Comment by koenedaele** [comment]
All dependencies have been released and frozen.

**Comment by koenedaele** [comment]
@BartSaelen I think everything's ready for the release, apart from the last french translations and the update of the Heroku demo.

I assume you can only update the demo to 0.4.1 after we've released 0.4.1?

Do you want to do the tagging and releasing on pypi? I'll write up messages for the Google Group (one to announce the release and one to announce the demo) and do the communications side.

**Comment by BartSaelen** [comment]
done, I'll update the demo later on

**Comment by koenedaele** [comment]
Ok, I'm closing this one.
