### ISSUE TITLE
Compilations of language files

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#195]
A user who wants to run the demo currently needs to run `python setup.py compile`. Is this actually necessary (if you're not changing any text)?

Can we include the compiled message catalogs in our distribution?

**Comment by koenedaele** [comment]
@TalissaJoly Can you take a look at this and see if and how this works?

**Comment by TalissaJoly** [comment]
For every language there is a .po file present. When running `python setup.py compile` a .mo is created using this .po file. I tried simply copying the .mo files into the correct folders and it seemed to work just fine. So I would say that if we could include these files in the distribution this command should no longer be necessary.

**Comment by cedrikv** [comment]
The biggest issue here is how to add the compiled .mo files to the scaffold, because right now we leave the mo files out of the git repo. So we either add them to git (in the locale folder next tot the po files), or create a separate folder in the demo scaffold to distribute them.
