### ISSUE TITLE
Handle HTML in notes

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#197]
Currently, our SKOS:notes are assumed to be text only. Mainly because in RDF a literal should not contain HTML. We would like our notes to be able to contain HTML. 

There does seem to be an rdf:HTML datatype that we could use. One possible problem here is that an RDF datatype can not have a language. So, something like "This is a <em>note</em>"@en is not possible. Which seems to suggest that we'll need to create a more complex object for holding our notes.

Things this impacts:
 * Admin user interface (add HTML editing)
 * Validation (validate incoming HTML, use some python equivalent of HTMLPurifier)
 * RDF serialising (in skosprovider_rdf)

**Comment by taeymma** [comment]
It's also possible to show the HTML in frontend with jinja2 filter: safe

**Comment by koenedaele** [comment]
Think everything in other libraries is in place to start work on this. Basically, allow some HTML in a Note. Tags I'd like to allow: em, strong, p, ul, ol, li and a. Ideally, all other tags would be stripped from user input upon submission. In the past we used HTMLPurifier for this with PHP, but I don't know if there's a good Python equivalent.

Other than that, reading from rdf with HTML in it and serialising to RDF with HTML in it still needs to be handled in skosprovider_rdf.

**Comment by vanbosa** [comment]
the dijit editor with it plugins is a possibility. with https://dojotoolkit.org/reference-guide/1.10/dijit/_editor/plugins/ViewSource.html. It as a source and preview function. The toolbar buttons uses <b> and <i> as tags but typing <strong> and <em> in the source  gives the same result.

filters are also a feature for stripping tags upon submission.

Something like the HtmlEditor from the Inventaris can also be used.

**Comment by vanbosa** [comment]
https://github.com/OnroerendErfgoed/atramhasis/issues/185 not usable for edit of notes in grid.

**Comment by koenedaele** [comment]
There's a python library called bleach that allows stripping of HTML tags based on a whitelist. Should be sufficient for our needs.

**Comment by koenedaele** [comment]
Handling HTML in RDF notes was added in OnroerendErfgoed/skosprovider_rdf#15

**Comment by koenedaele** [comment]
So, to summarize:

* skosprovider_rdf has been updated
* we need to be able to add HTML to notes in the admin interface. This also means setting the Markup attribute of a Note to 'HTML'
* we need to display the HTML in the frontend and not escape it.

**Comment by koenedaele** [comment]
UI has been added to the admin interface. What's left is backed work. More specifically:

* Validate incoming HTML with something like Bleach. Only tags allowed are strong, em and a.
* If after validation, the note still contains HTML, set the markup attribute (`skosprovider.skos.Note.markup`) on the Note to `HTML`. Otherwise, when serialising to RDF this will be serialised as the wrong datatype and will contain escaped HTML. Alternatively set everything that gets edited through the Atramhasis UI as `HTML`. Doesn't really hurt, but might make interoperability with other RDF systems that don't support the HTML datatype difficult.

**Comment by BartSaelen** [comment]
So to clarify, if a note contains only tags like strong, em and a, the markup attribute should not be set to HTML?

**Comment by koenedaele** [comment]
As soon as a HTML tag is present, markup should be set to HTML. Only tags we are allowing are strong, em and a.
