### ISSUE TITLE
Does an id have to be an integer?

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/atramhasis#206]
When a non existant id (integer) is used, 'resource not found is returned', see:
http://glacial-bastion-1106.herokuapp.com/conceptschemes/STYLES/c/123456789

When you do the same with a non existant id (string) you get a 'unexpected server error', see:
http://glacial-bastion-1106.herokuapp.com/conceptschemes/STYLES/c/non_existant

**Comment by koenedaele** [comment]
Skosprovider and pyramid_skosprovider allow for non-numeric id's. But Atramhasis doesn't. So, when testing if something is a valid concept, a cast to integer should be done. Skosprovider_sqlalchemy does this in https://github.com/koenedaele/skosprovider_sqlalchemy/blob/master/skosprovider_sqlalchemy/providers.py#L174, but we don't use this method in Atramhasis and have a custom method in the datamanager (https://github.com/koenedaele/skosprovider_sqlalchemy/blob/master/skosprovider_sqlalchemy/providers.py#L174)

**Comment by cahytinne** [comment]
I've only ran into the problem with the rdf.py view. The other views (views.py, crud.py, languages_crud.py) all include the `sqlalchemy.orm.exc.NoResultFound` exception and a 'resource not found' is raised with a non-existing string id.
