### ISSUE TITLE
405 Method not allowed

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#207]
Currently, when I send a request POST http://glacial-bastion-1106.herokuapp.com/conceptschemes, we get a 404 Not Found. In this case the correct answer would actually be a 405 Method Not Allowed, accompanied by an Allow header (eg. GET, HEAD).

Do we want to send 405 responses? How much work is at and for what value? Can we figure out a good way to generate this without writing a lot of custom code?

Any thoughts on this @maarten-vermeyen @dieuska @BartSaelen?

**Comment by BartSaelen** [comment]
Currently we don't send 405 responses. Shouldn't be too hard to support.
