### ISSUE TITLE
HTTP OPTIONS request

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#208]
Currently, we don't suppport OPTIONS requests. One of the possible applications is doing an OPTIONS request on a resource and the resource would then answer with the allowed methods.

```http
OPTIONS http://glacial-bastion-1106.herokuapp.com/conceptschemes

200 OK
Allow: GET, HEAD, OPTIONS
```

Do we want to do this (ie. is it worth it)? And how does play with things like CORS middleware?

Thoughts? @maarten-vermeyen @dieuska @BartSaelen

**Comment by BartSaelen** [comment]
HTTP Options is automatically supported by the cors middleware

**Comment by koenedaele** [comment]
I think wsgicors does this for CORS requests, but doesn't actually know what the underlying resource supports.

**Comment by koenedaele** [comment]
I've been reading a bit more about it. Lots of conflicting opinions. Might be a nice to have feature, but not particularly relevant. So, I'm closing this one for now.
