### ISSUE TITLE
Collect usage stats

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#214]
To be able to create some interesting visualisations of the data (#213), we need some data on what people are interested in. I think we need some kind of log table where we collect the following:

concept_visit_log
 * concept.id
 * timestamp
 * mime_type (text/html, application/json, application/rdf+xml, ...) or origin (html, REST, RDF)

I think this is enough data to be able to answer things like:

 * Get me the 10 most visitited concepts the past week
 * Get me the 5 most visited concepts the past week for conceptscheme 1
 * Get me the most frequently called concept through the rest interface

We might need a second table conceptscheme_visit_log to be able to see which conceptscheme pages are being visited.

**Comment by koenedaele** [comment]
@BartSaelen Could you review this ticket and if you think everything is OK, give it to @TalissaJoly for implementation?

**Comment by cahytinne** [comment]
Does origin CSV has to be logged?

**Comment by koenedaele** [comment]
Not sure if there's much use in it. But on the other hand, I don't think it hurts?
