### ISSUE TITLE
Add more example datasets

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#215]
Currently, we're shipping our conceptscheme of `styles and cultures` and `materials` with Atramhasis. These are good datasets, but still fairly simple when it comes to structure and data. Something more complex like our typologie dataset would be very useful.

So, let's go all the way and add these datasets with this config.

 * https://inventaris.onroerenderfgoed.be/thesaurus/typologie, id = HERITAGETYPE, uri = https://id.erfgoed.net/thesauri/erfgoedtypes/%s.
 * https://inventaris.onroerenderfgoed.be/thesaurus/datering, id = PERIOD, uri = https://id.erfgoed.net/thesauri/dateringen/%s
 * https://inventaris.onroerenderfgoed.be/thesaurus/soort, id = SPECIES, uri = https://id.erfgoed.net/thesauri/soorten/%s
 * https://inventaris.onroerenderfgoed.be/thesaurus/gebeurtenis, id = EVENTTYPE, uri = https://id.erfgoed.net/thesauri/gebeurtenistypes/%s

See https://github.com/OnroerendErfgoed/atramhasis/tree/master/fixtures for more info on these dumps. Maintain the two files (eg. eventtypes_data.py and eventtypes.py). Do NOT overwrite the existing two (styles and cultures and materials).

**Comment by cahytinne** [comment]
I was getting the data by the OnroerendErfgoedProvider following the other examples, but the provider does not support uri's. Should I include it in the provider or ignore the uri generation?

```python
    def get_by_uri(self, uri):
        warnings.warn(                                                          
            'This provider currently does not fully support URIs,\
             because the underlying service does not support them and URIs \
             have not been decided for these thesauri.',
             UserWarning                                                  
        )
        return False
```

**Comment by cahytinne** [comment]
Ok, I see. First the data is collected by the OnroerendErfgoedProvider and afterwards it is put into a DictionaryProvider with the UriPatternGenerator.
