### ISSUE TITLE
Navigation idea: show last visited concepts

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#217]
Allow the user to see a list of recently vistited concepts (visited by that user). We could probably just do this by sticking the last 5-10 concepts in the user's session.

Only thing is, I don't think we currently have a session? So, either we force the presence of a session. Or we provide the implementation with the option to have this session, provided they implement some session mechanism.

**Comment by BartSaelen** [comment]
back end part is done

**Comment by cedrikv** [comment]
The list is not restricted to unique values, so the same concept can be lsited multiple times:
![atramhasis](https://cloud.githubusercontent.com/assets/1849458/9461210/fe20017e-4b0c-11e5-9402-da0ed4d0ad1e.png)
