### ISSUE TITLE
create pyramid skaffold from atramhasis style

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/atramhasis#219]

**Comment by koenedaele** [comment]
Please explain what this is all about.

**Comment by dieuska** [comment]
@kmillet , dit is het ticket dat ik dinsdag voor de sprintmeeting had toegevoegd op vraag van u.
Kan jij de bedoeling hiervan aan Koen toelichten, (of is dit ticket hier overbodig geworden nu je een nieuwe repo 'atramhasisstijl' hebt bijgemaakt?)

**Comment by koenedaele** [comment]
Alos, please keep all Atramhasis discussions in English.

**Comment by dieuska** [comment]
I close this ticket and add this to 'atramhasisstijl'
