### ISSUE TITLE
Private conceptschemes

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#228]
Currently, when you open the HTMl interface, you are shown all thesauri, except for the external ones. But it might also make sense to define some thesauri as `hidden`. Thesauri who are public, but are hidden from normal users. So, they're visible in the JSON API, but not in the HTML interface. Or the can be found when accessing the URL directly, but are just hidden in the browsing interface.

Todo:
 * We can add the Subject `hidden` to a provider.
 * This means that in the opening screen and the search screens the provider does not show.
 * But if I go to the JSON Api, I can see it.
 * If I go to directly to the HTML version of a concept or the scheme, I can see it.

**Comment by cahytinne** [comment]
Does the provider also has to be in hidden in the admin interface?

**Comment by koenedaele** [comment]
No, it's basically a conceptscheme that doesn't easily show up for public users. We still need to be able to edit it.
