### ISSUE TITLE
Image for the new style

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#231]
In the new style, @TOM-VC wants to use an image as a background. Currently it's this one: https://github.com/OnroerendErfgoed/atramhasisstijl/blob/master/foundation/brainheadimg-light.png.

See 
![schermafdruk van 2015-08-05 15 04 36](https://cloud.githubusercontent.com/assets/676018/9086230/576a8dd8-3b83-11e5-90d3-f78949c14571.png)

Would be nice if we had something more in line with the Atramhasis theme. Could we eg. use an image of an Assyrian sphinx or so? @sophiemortier Seems like you might have a good idea for something like this?

/cc @taeymma

**Comment by sophiemortier** [comment]
God van de wijsheid in Mesopotamië?
![enki](https://cloud.githubusercontent.com/assets/3015670/9107001/73fd36fc-3c24-11e5-936f-d6b5e1599196.jpg)
Of sfinks: ook altijd mooi symbool voor wijsheid. 
![sfinx_mesopotamia](https://cloud.githubusercontent.com/assets/3015670/9107011/7ba290be-3c24-11e5-833a-2d7bacfaac5e.jpg)

**Comment by sophiemortier** [comment]
Maar Mesopotamie ken ik niet zo goed. 

Dit is meer mijn area of expertise: 
![ibis-logo-small](https://cloud.githubusercontent.com/assets/3015670/9107179/9d2770a0-3c25-11e5-9229-778486b68912.jpg)
![thoth_baviaan](https://cloud.githubusercontent.com/assets/3015670/9107178/9d22f2e6-3c25-11e5-9ddb-07288463c38b.jpg)

![dieu_thot](https://cloud.githubusercontent.com/assets/3015670/9107187/b0bb8232-3c25-11e5-8115-500e0c2ea0ac.jpg)
 god van het schrift/wijsheid; maar gebruiken we misschien beter niet, anders gaan ze denken dat we idioten zijn omdat we Meso en Egypte door elkaar halen.

**Comment by sophiemortier** [comment]
Of misschien iets met spijkerschrift?
<img width="110" alt="amarna_akkadian_letter" src="https://cloud.githubusercontent.com/assets/3015670/9107237/0d0cad7c-3c26-11e5-85af-c2f7b9461130.png">

**Comment by sophiemortier** [comment]
Is misschien wel gemakkelijk om iets abstracts van te maken:
![cuneiform-writing](https://cloud.githubusercontent.com/assets/3015670/9107263/4547881a-3c26-11e5-912b-fac8853b9408.jpg)

**Comment by sophiemortier** [comment]
Oe of deze: afbeelding van het verhaal van Atramhasis zelf zoals overgeleverd: 
![atrahasis_bm](https://cloud.githubusercontent.com/assets/3015670/9107502/faaf197e-3c27-11e5-9ab7-f708f5df2523.jpg)

**Comment by sophiemortier** [comment]
Of misschien kunnen we de kop van Gilgamesh gebruiken; het verhaal van Atramhasis maakt deel uit van het epos van Gilgamesh blijkbaar. En die kop is wel bekend, dus zelfs in geabstraheerde vorm bruikbaar?
![gilgamesh](https://cloud.githubusercontent.com/assets/3015670/9107619/fbad01a0-3c28-11e5-93fc-f0fced2a8862.jpg)

**Comment by koenedaele** [comment]
My favourites would be either the head of Gilgamesh or the Spijkerschrift. Do have to make sure we find a picture without copyright.

**Comment by sophiemortier** [comment]
I think in that case the cuneiform is the safest option. No copyright issues with just writing in cuneiform right?

**Comment by koenedaele** [comment]
There's no problem with the head or the cuneiform. Only the image could be copyrighted by the photographer. But I assule there must be public domain pictures of Gilgamesh's head or Cuneifrom. @maarten-vermeyen You can probably tell us more about this?

**Comment by TOM-VC** [comment]
This is something we can use. ( start with)
Making an abstraction of it ( illustration in vector for example ) also clears all copyright claims on the image because it's a newly created artwork.





Op 6-aug.-2015, om 10:50 heeft sophiemortier <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Of misschien kunnen we de kop van Gilgamesh gebruiken; het verhaal van Atramhasis maakt deel uit van het epos van Gilgamesh blijkbaar. En die kop is wel bekend, dus zelfs in geabstraheerde vorm bruikbaar?
[gilgamesh]<https://cloud.githubusercontent.com/assets/3015670/9107619/fbad01a0-3c28-11e5-93fc-f0fced2a8862.jpg>

**Comment by koenedaele** [comment]
Seems like it might actually be the head of Sargon of Akkad (https://en.wikipedia.org/wiki/Sargon_of_Akkad)? But, it really looks good, so we'll go with it.

**Comment by sophiemortier** [comment]
I have a feeling it is still a bit of a discussion point: it could also be Naramsin or Manishtishu. 
Anyways, the hairdress and style is mesopotamiam...

**Comment by koenedaele** [comment]
You win ;-)

But I agree, it's a very good head that will work well for what we want.

**Comment by taeymma** [comment]
New image:

![image](https://cloud.githubusercontent.com/assets/10401895/9443365/fbc90038-4a80-11e5-9ae6-1d90886666f3.png)

**Comment by TOM-VC** [comment]
ik ga er nog aan werken ( strakker en zuivere vormen) , maar voorlopig kan dit wel


Op 24-aug.-2015, om 16:55 heeft taeymma <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


New image:

[image]<https://cloud.githubusercontent.com/assets/10401895/9443365/fbc90038-4a80-11e5-9ae6-1d90886666f3.png>

**Comment by sophiemortier** [comment]
cool :-)

**Comment by koenedaele** [comment]
@TOM-VC Is this the final image or is still more work needed?

**Comment by taeymma** [comment]
I think this can be closed?
