### ISSUE TITLE
What's up with base, staticbase and page-layout templates?

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#247]
This seems to have changed in the latest version. If I recall correctly the reasoning was:

 * Staticbase.jinja2 contains the markup needed to function and defines a couple of blocks for css and js files that can be overriden.
 * By default base.jinja2 just extends staticbase.jinja2 but doesn't do anything.

The idea was that a client who made his own implementation would override base.jinja2 and provide eg. his own css file without having to overrride the entire template. So, the more static aspects (markup) where separated from some of the more dynamic aspects (css file).

In the current version, both files have been removed and a new page-layout.jinja2 has been added. I assume it's filling more or less the same role?

Anyway, it's still a goal of this project that an implementer should be a able to override presentation fairly easily. If we're changing how that's supposed to work, we need to make sure we've thought it through.

/cc @BartSaelen @cedrikv

**Comment by taeymma** [comment]
Added 2 new files: staticlayout-main.jinja2 and staticlayout-page.jinja2
These are extended in the layout-main.jinja2 and layout-page.jinja2. So an implementer can override the  blocks in these files.
The custom css/js blocks are still present and there are extra blocks for header/content/subfooter/footer.

Note: if an implementer overrides {% block js_files_head %} or {% block js_files %} a large part of foundation + tree functionality will not work..

**Comment by koenedaele** [comment]
Is there a good reason for having separate "master-templates" for the main page and a normal page? They seem quite similar? At first glance, the "-page" puts a few js files in the head that the main puts at the end of the body and there's bgcontainer that the main wraps around the content? Are there more differences, or is that all?

Is so, can't we do something like:
 * staticlayout.jinja2
 * layout.jinja2 (extends staticlayout)
 * layout-page.jinja2 (extends layout and overrides the js_head_files to add d3)
 * The bgcontainer declaration could just go to the homepage's template. If d3 is only needed for the detail of a concept, this should probably be an override of the js_head_files in that one template?

**Comment by taeymma** [comment]
Now we have:

* staticlayout.jinja2 (main template)
* staticlayout-page.jinja2 (template for subpages, with d3 and page imports)
* layout-page.jinja2 (overrideable file for implementers)
* specific layout for homepage is moved to home.jinja2
