### ISSUE TITLE
Conceptschemes for popular concepts are hardcoded

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#251]
The atramhasis/templates/subfooter-main.jinja2 template shows the most popular concepts or 4 conceptschemes.

Problems:
 * These are conceptschemes that are part of the development version. They will be different in every instance of Atramhasis
 * There's no guarantee that the instance will have 4 conceptschemes to show

Possible solutions:
 * Pick max. 4 conceptschemes at random?
 * Allow configuring the conceptschemes in the ini file?
 * Allow configuring and fallback to 4 random schemes when no configuration exists?
 * Make sure that the css works as well when there's only 1 or 2 conceptschemes

/cc @BartSaelen

**Comment by taeymma** [comment]
How would the conceptschemes be specified in the ini file?
something like:

top.conceptschemes = 'HERITAGETYPE', 'PERIODS', 'SPECIES', 'EVENTTYPES'

**Comment by koenedaele** [comment]
Use pyramid's as_list function (https://github.com/Pylons/pyramid/blob/master/pyramid/settings.py#L23).

Please call the variable `layout.focus_conceptschemes`.

So, this should look something like:
```ini
layout.focus_conceptschemes = 
 HERITAGETYPES
 PERIODS
 SPECIES 
 EVENTTYPES
```

This will require some custom parsing of the ini file. Similar to eg. https://github.com/Pylons/pyramid_debugtoolbar/blob/master/pyramid_debugtoolbar/__init__.py Most pyramid projects do something similar somewhere...

**Comment by taeymma** [comment]
@BartSaelen
