### ISSUE TITLE
DELETE language

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#257]
When writing some docs for the languages services, I was experimenting with the service for languages.

I noticed that I could delete a language that was being used in labels and notes. This was while using SQLite. Referential integrity can be used, but it needs to be configured. See http://stackoverflow.com/questions/2614984/sqlite-sqlalchemy-how-to-enforce-foreign-keys Not sure how we can do this cleanly, but it would make more sense to do this.

Also, based on reading the code, I'm assuming that deleting a language that's still in use on e.g. Postgresql will generate a SQLAlchemy exception that will lead to a HTTP 500 Internal Server Error. It seems like this is another good case for a HTTP 409 Conflict error, just like we're doing with the protected operations?

I'm currently adding this to the 0.5.0 milestone, but I'm open to moving it to a later version as well. Depends a bit on what we decide to do with it.

**Comment by koenedaele** [comment]
I assume SQLAlchemy raises an IntegrityError in these cases: http://docs.sqlalchemy.org/en/latest/core/exceptions.html#sqlalchemy.exc.IntegrityError. This is a  wrapper around a DBapi error: https://www.python.org/dev/peps/pep-0249/#integrityerror.

It would make sense to capture all sqlalchemy.exc.IntegrityError and turn these into HTTP 409 Conflict errors.

**Comment by taeymma** [comment]
At the moment this is caught in the frontend by placing a '-' when a language isn't present anymore.

**Comment by koenedaele** [comment]
I would prefer to handle this server side since it impacts a lot more than just the UI. Generally speaking, when not present the language should be treated as `und` (Undetermined).

```
Type: language
Subtag: und
Description: Undetermined
Added: 2005-10-16
Scope: special
```

Maybe we need to make sure this value is always present as a language?

**Comment by BartSaelen** [comment]
The IntegrityError is already present, just updated it a bit. Should be a warning in the logs I think.

> Postgresql will generate a SQLAlchemy exception that will lead to a HTTP 500 Internal Server Error.
This is not the case, returns as a 409

Handling Referenetial Integrity in Sqlite should be handled in https://github.com/koenedaele/skosprovider_sqlalchemy.

So, only problem that is left here, is to handle the 409 in the frontend @taeymma

**Comment by koenedaele** [comment]
Don't think we can set sqlite to handle referential integrity in skosprovider_sqlalchemy. Since that would require skosprovider_sqlalchemy to know what kind of connections you're running. I think it makes the most sense to configure this in an instance of Atramhasis. And thus leave it up to the implementer.
