### ISSUE TITLE
UI: sources

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#261]
Sources were added in #199 

Still todo:

* [x] Display sources in public frontend.
* [x] Allow editing of sources in admin interface

A concept, collection or conceptscheme has 0, 1 or more sources.

For the time being a source is an object with a single attribute "citation". Please treat all of this as if there was no object. No need to show that citation attribute. So, just something like:

```html
<p>Sources</p>
<ul>
 <li>Source 1</li>
 <li>Source 2</li>
</ul>
```

**Comment by koenedaele** [comment]
@taeymma please discuss UI with @TOM-VC if needed

**Comment by taeymma** [comment]
Issue while saving: 
multiple saves of a concepts keeps adding sources to the concepts instead of overwriting existing with saved values.

eg:
save concept with 1 source => ok.
save same concept again => source is present twice.

@BartSaelen
