### ISSUE TITLE
Add timezones to datetime and timestamp fields

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/atramhasis#263]
A timezone needs to be explicitly added to all datetime and timestamp fields. We need to add the timezone in the database via alembic, as well as in the python views.

A discussion (in Dutch)  why to add an explicit timezone can be found at https://github.com/OnroerendErfgoed/documentgenerator/issues/93

ALEMBIC:

Add the timezone attribute to an existing sqlalchemy field
```
op.alter_column(
        table_name='tablename',
        column_name='colname',
        type_=sa.TIMESTAMP(timezone=True)
    )
```

Add a new table with timestamp and datetime field
```
from sqlalchemy.sql import func
op.create_table(
    'tablename',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_timezone', sa.TIMESTAMP(timezone=True), server_default=func.now(), nullable=False),
    sa.Column('datetime_timezone', sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
)
```

PYTHON views:

explicit add timezone on current time:
```
from datetime import datetime
from pytz import timezone
tz_brussels = timezone('Europe/Brussels')
nu = datetime.now(tz_brussels)
```

explicit add timezone on specified time:
```
from datetime import datetime
from pytz import timezone
tz_brussels = timezone('Europe/Brussels')
datum_tmp = datetime(2015, 6, 12, 15, 30, 20)
datum = tz_brussels.localize(datum_tmp)
```

**Comment by koenedaele** [comment]
Please keep all Atramhasis communications in English.

**Comment by goessebr** [comment]
atramhasis is a database independent application. Since SQLite does not support timezones we won't implement them at all.
