### ISSUE TITLE
inconsistentie data

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasis#265]
Bij het ophalen van een concept zit in bv 'broader' een lijst van objecten. Bij de save wordt hier precies een lijst van id's verwacht.

Zou het niet logischer zijn dat bij het saven een lijst van objecten met enkel id wordt doorgestuurd dan?

EDIT: ook niet echt duidelijk in de docs aangezien daar nergens relaties of matches zijn ingevuld.
http://atramhasis.readthedocs.org/en/latest/services.html#write-services

**Comment by koenedaele** [comment]
Even vlug naar de server side code gekeken: https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/validators.py#L63

Als ik het zo lees staat er denk ik dat Broader een lijst van RelatedConcepts is en dat een RelatedConcept een id heeft en dus een object is. Maar ik heb al een tijdje geen colander schema's meer gelezen, dus ik kan er naast zitten ook. @BartSaelen ?

**Comment by BartSaelen** [comment]
Lijst van objecten met enkel id zou het moeten zijn. Die lijst van ids is een oude versie.

**Comment by koenedaele** [comment]
@BartSaelen en @taeymma I believe this one can be closed?
