### ISSUE TITLE
Maintain compatibility between Atramhasis and pyramid_skosprovider

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#266]
I think some of the services are no longer the same between Atramhasis and pyramid_skosprovider, most notably the handling of lists of concepts in relations (ie. the broader or related concepts). I think Atramhasis works with lists of objects while pyramid_skosprovider uses lists of ids. Most sensible option is probably to alter pyramid_skosprovider. Is more future-proof anyway.

**Comment by koenedaele** [comment]
Noticed because of #265

**Comment by koenedaele** [comment]
In https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/renderers.py#L137 we include the entire labels array. Do we really need this? Is this being used somewhere? I would prefer leaving this out and just giving the "best" suited label. This was added for 0.3.0, but I'm not sure if we ever used it.

@cedrikv @BartSaelen @taeymma

**Comment by koenedaele** [comment]
Any word on why we're include the whole labels array?

**Comment by taeymma** [comment]
In the public frontend the correct label is retrieved in the labels array.  Private frontend this array is not used, only 'label'.

> {{ c.label(request.locale_name).label }}

**Comment by koenedaele** [comment]
Ok, thx. I've removed the labels. Back in sync now.
