### ISSUE TITLE
Upgrade js dependencies

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#275]
See https://www.versioneye.com/user/projects/54f8ce754f3108e7800000a9#tab-dependencies

Think we should update dojo to 1.11 and dGrowl to 0.1.3. Not sure how easy it is to upgrade dgrid to 1.0.0 and Font-Awesome to 4.6.1

**Comment by taeymma** [comment]
dgird 1.0.0 shouldn't be a problem, and dojo is in all other applications on version 1.10.5, not sure if this is easily upgraded to 1.11.
font-awesome can be updated to 4.6.1

**Comment by koenedaele** [comment]
Everything upgraded. We left dojo at 1.10.5
