### ISSUE TITLE
problem with popular concepts

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasis#277]
When a concept is removed while still in the popular_concepts list this will give an error in the pub frontend when retrieving popular concepts.
The solution is probably to check when removing a concept if its present in one of the lists (popular/recent/..) and remove it.

**Comment by koenedaele** [comment]
Possible solutions I can see:

* Delete them from the visit log when they are deleted from the concepts table
* Keep them in the visist log to show that they did exist but filter them out when retrieving the list.

Second option is nice, but probably adds a lot of overhead for not so much gain. Think the first one is simpler to implement. @BartSaelen ?

**Comment by taeymma** [comment]
I implemented a fix that the concepts that aren't found are filtered out of the list.
