### ISSUE TITLE
More information on match when adding them

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#279]
I want to add a match to Heist (deel van Knokke-Heist). I click on add a match, select the `Thesaurus of Geographic Names` and search for Heist. I get 7 results. For each I see the prefLabel, the id and the type. If I want to know more about the concept, I need to create a new url like vocab.getty.edu/tgn/<id> and type that in a new browser tab. Would be nice if this was easier.

Options:
 * Provide some kind of dialog that gets that info from our service
 * Just add an external link icon that opens the URI of the concept in a new tab in the browser.

@taeymma I think the second option is fairly simple, so I would like to go with that at the moment. Is that doable for 0.5.0? More of a nice to have than a need to have.

**Comment by taeymma** [comment]
At the moment I implemented the second option.
The first option can be very slow due to the call to a external service.
