### ISSUE TITLE
UI: Improved handling of languages

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#288]
Currently you can't edit a language description after adding it. You can only delete the language and add it again, but that doesn't work well when you take #257 into consideration. So, we should be able to edit a language description.

Also, when adding a language, I need to specify a description. But I think we could actually let language-tags generate one. But that's a nice to have.

**Comment by taeymma** [comment]
The validation for languages happens serverside. Frontend only requires a language code, no description. Error is raised in backend.
