### ISSUE TITLE
Backend handling of sources

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasis#291]
Issue while saving: 
multiple saves of a concept keeps adding sources to the concept instead of overwriting existing with saved values. Because of this, sources cant be removed.

eg:
save concept with 1 source => ok.
save same concept again => source is present twice

This is rather annoying when testing. The sources keep multiplying each save..

refs https://github.com/OnroerendErfgoed/atramhasis/issues/261

**Comment by taeymma** [comment]
One of my concepts I use for testing now has around 6000 sources :cold_sweat:

**Comment by koenedaele** [comment]
This was not a bug.  :wink:  It was an intentional test to see if the system would be able to handle having an enormous amount of sources. Test results were satisfactory.
