### ISSUE TITLE
Display of matches

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#305]
When displaying matches in the public frontend, we seem to be showing info about the concept itself, not the match.

Currently, we're showing the label (presumably of our concept, not the match), the id (of our concept) and the type (no idea whose). This should be the label and id of the match.

Also, if I link to two different thesauri, I get two matches but I can't see with what conceptscheme. Can we inlcude some info of the external vocab here? A label or a uri?

**Comment by taeymma** [comment]
Ok, just checked.. and I don't have the info of the match available in the frontend. I thought the match.concept was the info of the match, but it isn't. In that case I only have the URI to show in the frontend. 
Is it possible to retrieve the label of the match in the backend? I don't want to do a rest call in the frontend (which is strange in a jinja template...)

**Comment by taeymma** [comment]
Use registry.get_by_uri() to retrieve the match.
