### ISSUE TITLE
Link from public frontend to backend for conceptschemes

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#307]
In the public front end, when visiting a concept scheme detail page, eg. `/conceptschemes/STYLES`, we have an "edit" link symbolised by a pencil. Clicking on this link brings us to `/admin`. But it would be nice if this would open the conceptscheme edit page by default. Unless this is not always possible because the user has no right to see the edit page?

**Comment by taeymma** [comment]
A conceptscheme doesn't have a detail page in the private frontend. I think I could open the edit dialog of the conceptscheme.. ok?
