### ISSUE TITLE
Conceptscheme.uri is required

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#316]
In koenedaele/skosprovider_sqlalchemy#24 the attribute conceptscheme.uri has been made required (as a result of #292). We need to update our database definitions to reflect this. Also, I think `atramhasis/scripts/import_file` will need to be updated because it doesn't create a conceptscheme.uri at the moment.

**Comment by BartSaelen** [comment]
And what should be the URI of the conceptscheme?

**Comment by BartSaelen** [comment]
Input via commandline?

**Comment by BartSaelen** [comment]
added commandline param --conceptscheme_uri
