### ISSUE TITLE
update scaffolds

### ISSUE THREAD

**Issue by BartSaelen** [OnroerendErfgoed/atramhasis#324]
The demo scaffold contains outdated requirements files. Time for an update.

**Comment by koenedaele** [comment]
Pretty sure I ran prepare and committed that. I thought that command updated those?

**Comment by BartSaelen** [comment]
Need to check, they are not up to date after running scaffold. So either they are not correct or the prepare command isn't working properly.

**Comment by koenedaele** [comment]
This was the result of prepare:

https://github.com/OnroerendErfgoed/atramhasis/commit/a59e2e490ff4058da52bc9c4c2f49f5611d45c6b

**Comment by BartSaelen** [comment]
after scaffold
```
# pyramid
pyramid==1.5.4
pyramid-tm==0.10
pyramid_rewrite==0.2

# skos
skosprovider==0.5.2
skosprovider_sqlalchemy==0.4.2
pyramid_skosprovider==0.6.0
skosprovider_rdf==0.4.0
skosprovider_getty==0.2.1
skosprovider_heritagedata==0.2.1

#language-tags
language-tags==0.3.1

# sqlalchemy
sqlalchemy==0.9.8
zope.sqlalchemy==0.7.5
transaction==1.4.3
psycopg2

# jinja2
jinja2==2.7.3
pyramid-jinja2==2.3.3
Babel==1.3

# alembic
alembic==0.7.4

# colander
colander==1.0

# caching
dogpile.cache==0.5.6

# other
six==1.6.1
requests==2.5.1

```

**Comment by BartSaelen** [comment]
looks like I have an older version of Atramhasis, checking that first

**Comment by BartSaelen** [comment]
Ok, was just a problem with wrong version
