### ISSUE TITLE
Icon disappears when editing

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#326]
When editing notes (or labels), the garbage bin icon is not visible.

Don't think I've seen this on my local install, so I could just be an issue with the demo at Heroku. That might indicate it's a packaging problem.

![image](https://cloud.githubusercontent.com/assets/676018/17624913/f2249adc-60a6-11e6-9453-5e485bdc8bc4.png)

**Comment by taeymma** [comment]
Not able to reproduce local..

**Comment by koenedaele** [comment]
I'm going to assume this was a duplicate of #330
