### ISSUE TITLE
UI text

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#327]
Some of the public front UI still needs proper labels:

* VIEW_RELATIONS
* VIEW_TREE
* POPULAR_CATEGORY
* RECENTLY_VIEWED

**Comment by taeymma** [comment]
They are all present in the .po of the locale files.

**Comment by BartSaelen** [comment]
Labels are present, might be an issue with compile catalog

**Comment by koenedaele** [comment]
Sorry, my bad.
