### ISSUE TITLE
Difference between demo and dev version

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#328]
In "normal" version, the frontpage show 4 categories with popular concepts. In the demo, these are absent. Some configuration in the scaffold is missing?

**Comment by taeymma** [comment]
in dev.ini:

```
layout.focus_conceptschemes =
  HERITAGETYPE
  PERIOD
  GEOGRAPHY
  MATERIALS
```

**Comment by taeymma** [comment]
Needs fix in atramhasis/init.py @BartSaelen
