### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#330]
At http://glacial-bastion-1106.herokuapp.com/admin# the Menu icon is missing and the spinner to indicate that matches are loading is missing.

I assume this is a packaging problem.

**Comment by taeymma** [comment]
This seems to be a missing bower install in the /static/admin folder

**Comment by taeymma** [comment]
Ok, my mistake. This is because the style of atramhasis isnt copied in the scaffold. I'll update the demo scaffold also.

**Comment by koenedaele** [comment]
@BartSaelen Can we update the prepare task so that the style is copied everytime we run this command?

**Comment by BartSaelen** [comment]
@taeymma can you list the files and directories that need to be copied each time?

**Comment by taeymma** [comment]
/static/* except .sass-cache and bower_components
/static/admin/.bowerrc - bower.json - package.json - grunfile.js
