### ISSUE TITLE
Add tree view to conceptschemes

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#334]
Currently, when starting from the conceptscheme page there is no tree view. Can we add the tree view from concept here as well?

/cc @sophiemortier

**Comment by koenedaele** [comment]
We will add the tree view to the conceptscheme and drop the top concepts (they are not very usefull anyway). To make discovering the conceptscheme easier, we will add tiles to the frontpage that link to the schemes.

**Comment by taeymma** [comment]
![atramasis_main_w_blocks](https://cloud.githubusercontent.com/assets/10401895/18274649/bbf56f58-7443-11e6-8b46-1c8e54bc6eb0.png)
![atramhasis_conceptscheme](https://cloud.githubusercontent.com/assets/10401895/18274650/bbfb18ae-7443-11e6-8f42-dc915f3c0768.png)

**Comment by taeymma** [comment]
I think I will enhance the tree with a drag/pan/zoom functionality as shown in this example: 
http://bl.ocks.org/robschmuecker/7880033

**Comment by taeymma** [comment]
I made some improvements to the current tree. Ill merge this for the beta2 release tomorrow (thursday). The enhancements (drag/pan/zoom) of the tree will take some time. It doesn't look easy..

**Comment by koenedaele** [comment]
Ok, I don't think we need the dragging. Panning and zooming would be nice.
