### ISSUE TITLE
Add list of conceptschemes

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#339]
Currently every page shows a small list "Volg Atramhasis". It's not that useful. Let's replace it with a list of all the available conceptschemes.

/cc @TOM-VC

**Comment by taeymma** [comment]
I noticed a problem in Thesaurus with this list. I only have uri's to link to.. should i build the url with the id of the conceptscheme instead? the uri's aren't working and initate a redirect throught id.erfgoed.net/thesauri/<schemeId>

**Comment by taeymma** [comment]
I think this should be fetched with request.route_path('conceptscheme', scheme_id=item.id)
