### ISSUE TITLE
Fine tune requirements files

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/atramhasis#348]
atramhasis-requirements-dev.txt is a little obsolete in the scaffolds..

**Comment by koenedaele** [comment]
Possibly. I assume it is, but I doesn't seem to hurt either?

/cc @BartSaelen

**Comment by taeymma** [comment]
I failed to run pip install after rolling out the scaffold in thesaurus.

**Comment by cahytinne** [comment]
> I failed to run pip install after rolling out the scaffold in thesaurus.

Problem fixed in thesaurus OnroerendErfgoed/thesaurus#41
