### ISSUE TITLE
Copy alembic files to scaffolds

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#349]
Let's add the alembic files to scaffolds as well. That way, an implementation can maintain it's own alembic migrations. Whenever an Atramhasis update is scaffolded in, the user should create a new merge? Not sure if this will work cleanly.

**Comment by koenedaele** [comment]
@cedrikv We should see how we want to handle this or not. Think you solved some things for the last version of thesaurus. So, maybe this ticket is no longer necessary.

**Comment by cedrikv** [comment]
No proper solution yet, I just created new alembic versions in thesaurus with the updates from atramhasis.

**Comment by koenedaele** [comment]
@Wim-De-Clercq Is this something you can look into? The basic problem is that we have alembic migrations in our base package (atramhasis), but that we sometimes want to add migrations to our implementation package (thesaurus in our case) as well, eg. when we add a new conceptscheme. In this case, when we update to a new version of Atramhasis it has no knowledge of the alembic revisions that were created in the local package. Currently, we're just copy-pasting new alembic migrations and doing manual fixes. But is there a better way? Using alemic branches in some way (https://alembic.sqlalchemy.org/en/latest/branches.html)? Or something completely different?

**Comment by Wim-De-Clercq** [comment]
I do indeed think the branches could be a solution, yes. I'll have to test it a bit to be sure though.

**Comment by Wim-De-Clercq** [comment]
I did some testing and the following works:
- delete all atramhasis revision copies from thesaurus. What's left:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/4599667/90388711-87fe8580-e088-11ea-9620-f9e227eff8cf.png">
- In thesaurus I made the first revision look like
```python
revision = '5cfd7365fc93'
down_revision = None
depends_on = '3bcf11802900'  # this is a revision  in atramhasis project

branch_labels = ('thesaurus',)
```
I also added an atramhasis label in atramhasis project.

Then in the `alembic.ini` I added
```
version_locations = %(here)s/alembic/versions atramhasis:alembic/versions
```
And then setting everything up looks like:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/4599667/90388936-f2172a80-e088-11ea-8d89-1ba82a8daf15.png">


Everything works fine as of yet, but I do still have an open question that I can't find a solution for, so I asked it in the alembic repo.
https://github.com/alembic/alembic/issues/299

When that is resolved, all that's left is I must make sure that an upgrade from the current installed revision to this new revision setup works flawlessly for dev/test/prod servers.

**Comment by Wim-De-Clercq** [comment]
The following (little hacky) code can be used to add a custom depends_on to add a dependency within atramhasis revisions:
```py
with context.begin_transaction():
    revision_map = context.script.revision_map
    revision = revision_map._revision_map['b04fd493106b']
    revision.dependencies = '5cfd7365fc93'
    revision_map.add_revision(revision, _replace=True)
    context.run_migrations()
```
This is code in `alembic/env.py` in the thesaurus project.

We don't need it now, but I write it here so that hopefully when someone in the future needs they may see it.

**Comment by Wim-De-Clercq** [comment]
Momenteel kopieert thesaurus dus alle nieuwe revisions over in z'n eigen alembic.

Liefst zou ik dit willen veranderen dat in alembic.ini er simpelweg dit wordt geconfigureerd:
```
version_locations = %(here)s/alembic/versions atramhasis:alembic/versions
```
Dan worden alle revisions van atramhasis automatisch gebruikt bij andere projecten, zoals thesaurus.
Projecten zouden dan 2 alembic branches hebben lopen
```
atramhasis: ahash1 > ahash2 > ahash3 > ahash4
thesaurus: thash1 > thash2
```
Er zijn dan ook 2 heads in de `alembic_revisions tabel in de DB, deze bevat 2 rijen: ahash4 en thash2

Het is, imo, veruit de properste project opzet. Bij updates van atramhasis worden de revisions automatisch gezien en uitgevoerd. 
Maar het probleem zit hem in het bestaan van huidige atramhasis projecten (zoals thesaurus) en de omzetting naar de nieuwe opzet als we dit zouden updaten.

Ik kan wel de revisions binnen thesuaurs opkuisen, en manuele database changes doen in de alembic_revisions tabel om alles recht te zetten. Maar wat als er in de wereld nog andere projecten zijn die atramhasis gebruiken, ik denk niet dat we eenvoudig kunnen vragen om al hun revisions even manueel correct te zetten....

**Comment by cedrikv** [comment]
@Wim-De-Clercq We are missing an estimate for this one
