### ISSUE TITLE
Mozilla persona service is shutting down

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#361]
November 30th. See https://login.persona.org/

So our demo will be unavailable pretty soon.

Anything similar out there we can use?

**Comment by maarten-vermeyen** [comment]
Maybe roll our own Keycloak server and use velruse or something similar to authenticate against it's OpenID endpoint? Keycloak doesn't seem that hard to setup, although the SSL requirement for the client application might be an issue.

**Comment by koenedaele** [comment]
Looks interesting. Not sure if it's easy enough to work as a replacement for the demo though.

**Comment by koenedaele** [comment]
Think this might be easier to integrate in the demo: https://github.com/fizyk/pyramid_fullauth ?

**Comment by koenedaele** [comment]
Current solution is to remove all authentication from the demo.
