### ISSUE TITLE
Support for SortLabel

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#362]
Present in skosprovider 0.6.0 and skosprovider_sqlalchemy but not in Atramhasis. Will require a minor db update and a minor UI update.

**Comment by taeymma** [comment]
What has to be changed in the UI?

**Comment by cahytinne** [comment]
When https://github.com/koenedaele/pyramid_skosprovider/pull/27 is merged, a new release of pyramid_skosprovider is required and, consequently, an update of the requierements file in this project is required.

**Comment by koenedaele** [comment]
> ~~What has to be changed in the UI?~~
>
>EDIT: Label can be added and viewed in admin, should this label be visible on the concept details? 

@taeymma I think the sortLabel is a specific type of hiddenLabel. I've looked at https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/templates/macros.jinja2#L15 and we seem to render those in the concept details, so I would add the sortLabel as well.

**Comment by koenedaele** [comment]
pyramid_skosprovider 0.8.0 has been released. See https://pypi.python.org/pypi/pyramid_skosprovider

**Comment by koenedaele** [comment]
@cahytinne Will you update this branch and sync it with dev_0_6?

**Comment by koenedaele** [comment]
@cahytinne @taeymma Can we finish this one, is probably the only remaining issue for the release.

**Comment by cahytinne** [comment]
- [x] backend
- [ ] frontend

**Comment by koenedaele** [comment]
Just checked out this branch and tried to edit the labels for a concept. When I open the period '10de eeuw' for editing, I can not see any labels. Yet, in the read part of the edit interface they are present.

Reading:

![image](https://user-images.githubusercontent.com/676018/28288600-099e2ac6-6b40-11e7-8e2c-5a8a1c8570ae.png)


Editing:

![image](https://user-images.githubusercontent.com/676018/28288623-19013cb0-6b40-11e7-87e4-d068d7342714.png)

**Comment by koenedaele** [comment]
Since nothing has changed in this branch yet, I assume it's also present in version 0.6.0

**Comment by cedrikv** [comment]
Created separate issue for the problem of the missing labels.

**Comment by steuraa** [comment]
![image](https://user-images.githubusercontent.com/14195346/28311058-c3700ea6-6bae-11e7-9144-b793181949f4.png)

Added labelType Sort in edit menu. Added extra label to jinja and hidden + sort to admin detail page

**Comment by cedrikv** [comment]
fixed in dev_0.6
