### ISSUE TITLE
Problems with tree cache

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#371]
The tree cache as defined in https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/views/__init__.py is rather limited. It's hardcoded to an in-memory cache and is not easy to modify by an implementor to eg. a redis cache.

This make it hard to run a load-balanced version of Atramhasis. Suppose we are running two servers (A and B), and a user commits changes on server A. Currently, the cached tree on server B is not cleared.

**Comment by BartSaelen** [comment]
huidige invalidate scheme cache gaat niet werken met andere implementaties van de cache region backend

**Comment by BartSaelen** [comment]
now running in to DetachedInstanceError issues. This is way more complicated than just configure the regions from settings

**Comment by BartSaelen** [comment]
Simple solutions is to leave out the custom invalidate stuff and to just invalidate the region. This will also solve the cache problems in https://github.com/OnroerendErfgoed/thesaurus/issues/37
