### ISSUE TITLE
Wrong concept uri's after file import

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/atramhasis#372]
When using the import_file script, all the concept uri's have the default format of "urn:x-skosprovider:wetgeving:xxx"

Command used for import:
`import_file --from wetgeving.json --to postgresql://xx:yy@localhost:5432/thesaurus --conceptscheme_uri https://id.erfgoed.net/thesauri/wetgeving`

Script output:
```
*** The import of the wetgeving.json file with conceptscheme label 'Wetgeving' to postgresql://xx:yy@localhost:5432/thesaurus was succesfull. ***          

To use the data in Atramhasis, you must edit the file my_thesaurus/skos/__init__.py.          
Add next lines:           

def includeme(config):                
        WETGEVING = SQLAlchemyProvider(                    
                {'id': 'WETGEVING', 'conceptscheme_id': 9},                    
                config.registry.dbmaker                
        )                
        skosregis = config.get_skos_registry()                
        skosregis.register_provider(WETGEVING)
```

file:
[wetgeving.txt](https://github.com/OnroerendErfgoed/atramhasis/files/1105202/wetgeving.txt)
renamed to .txt for github supprt

**Comment by koenedaele** [comment]
Could you add that wetgeving.json file?

**Comment by cedrikv** [comment]
updated in ticket

**Comment by koenedaele** [comment]
Normally, the import respects the concept URI's in the file. But there are none. In that case it generates a URI based on the configured urigenerator. I loks like you didn't configure one. So, it falls back to the default generator, which generates `urn;x-skosprovider:wetgeving:xxxx`.

Think you need to try something like this:

```
WETGEVING = SQLAlchemyProvider(
        {'id': 'WETGEVING', 'conceptscheme_id': 9},
        config.registry.dbmaker,
        scheme_uri='https://id.erfgoed.net/thesauri/wetgeving',
        uri_generator=UriPatternGenerator('https://id.erfgoed.net/thesauri/wetgeving/%s')
    )
```

**Comment by cedrikv** [comment]
Doesn't help. I don't think the provider is used during the import.

**Comment by BartSaelen** [comment]
The one in the commandline is the URI for the concecptscheme, not the URI pattern for the provider. Needs further investigation.

**Comment by koenedaele** [comment]
Ah, figured it out. Depending on the filetype of the file (eg. .json), a function like https://github.com/OnroerendErfgoed/atramhasis/blob/master/atramhasis/scripts/import_file.py#L54 is called. In that function, a provider is created that handles the file to be imported. But, it's not configured with a URI generator, so it falls back on the default generator.

I assume this problem will not exist when importing an RDF file because a URI is mandatory there.

So, to solve this we could allow passing a URI pattern to the script that is used with a skosprovider.uri.UriPatternGenerator. If this doesn't work for all types of patterns, the user doing the importing can always just provide the URI's in the file to be imported.

@BartSaelen @cedrikv Thoughts?

**Comment by cahytinne** [comment]
The import of 'wetgeving' indicated above with uri pattern will now work with following command:
```shell
import_file --from wetgeving.json --to postgresql://xx:yy@localhost:5432/thesaurus --conceptscheme_uri https://id.erfgoed.net/thesauri/wetgeving --pattern_uri https://id.erfgoed.net/thesauri/wetgeving/%s
```
If the language_id of the preflabel conceptscheme is changed into 'nl', see: https://github.com/OnroerendErfgoed/atramhasis/commit/e22e8738699e64467e1649d3474c1ad5e6dac918#commitcomment-23029544

**Comment by cedrikv** [comment]
@cahytinne the import script expects '--pattern_uri' instead of '--pattern_uri'  like you mentioned.

**Comment by cahytinne** [comment]
@cedrikv 
I'am little confused by your comment. You say twice '--pattern_uri' But I see. I have made a mistake with the example code. I should the '--uir_pattern' like this:

> ```
>import_file --from wetgeving.json --to postgresql://xx:yy@localhost:5432/thesaurus --conceptscheme_uri https://id.erfgoed.net/thesauri/wetgeving --uri_pattern https://id.erfgoed.net/thesauri/wetgeving/%s

**Comment by cedrikv** [comment]
fixed my typo :)
