### ISSUE TITLE
Update language-tags to 0.4.3

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/atramhasis#376]
after https://github.com/OnroerendErfgoed/language-tags/issues/16

**Comment by Pieter-Beckers** [comment]
uitgevoerd door @cahytinne in https://github.com/OnroerendErfgoed/atramhasis/commit/6aa06016e7f7c7f960a98a0235eb3ce832fb8f25

**Comment by cahytinne** [comment]
Juist, ik had het ticket niet gezien.
