### ISSUE TITLE
Not possible to edit labels

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/atramhasis#384]
Labels are not visible in edit mode, see https://github.com/OnroerendErfgoed/atramhasis/issues/362#issuecomment-315875023

**Comment by steuraa** [comment]
![image](https://user-images.githubusercontent.com/14195346/28309415-951f9f1c-6ba9-11e7-97ba-0c4246018312.png)
@koenedaele tried to reproduce the missing label issue, but it seems to work properly here. Adding/deleting labels doesn't produce any errors.

**Comment by koenedaele** [comment]
I only had issues with one concept. Couldn't reproduce last time.
