### ISSUE TITLE
Adding a simple printable tree structure

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#406]
For a lot of purposes, a print of a conceptscheme as a hierarchy would be useful. We would like to keep this simple as an HTML page. Something like this:

![image](https://user-images.githubusercontent.com/676018/31589383-da7bcf3e-b200-11e7-8dcd-51b5035339af.png)

Let's reuse the /tree endpoint with an Accept header of text/html. So, https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/tree would be the HTML tree for ERFGOEDTYPES.

All we need to do then is add a link from https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES to https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/tree.

**Comment by axd1967** [comment]
https://trac.onroerenderfgoed.be/toepassingen/ticket/1849
