### ISSUE TITLE
Access Admin page on local install

### ISSUE THREAD

**Issue by fvepwc** [OnroerendErfgoed/atramhasis#417]
How can I access the admin page on the demo running locally?
If I click the admin link on the top right of the main page, I get this:

![image](https://user-images.githubusercontent.com/33900196/33265090-8e27a388-d370-11e7-8e2b-231cabdbe7e9.png)

I don't see where I could log in (the "sign-in button" is not clickable) and have no idea what credentials to use if I would know where to log in.

Best,
Frederik

**Comment by koenedaele** [comment]
This used to be an integration with the Mozilla Persona service. But Mozilla has discontinued this service.

The default version of Atramhasis does not come with an authentication mechanism. We ourselves use our integration with ACM/IDM for https://thesaurus.onroerenderfgoed.be.

I'll see what the easiest way to disable authentication for the demo is.

**Comment by koenedaele** [comment]
As a quick fix, try this:

In your local demo environment (atramhasis_demo) there's a file __init__.py Open this file with a text editor, go to line 42 and comment lines 43-47. In Python, you do this by adding a # character.

In that same folder there's a file called security.py. In this file comment lines 26 and 27, the ones starting with @view_config(). You can probably also just delete the entire file.

Commenting these lines gives you an installation where you admin interface can be used by anybody.

**Comment by fvepwc** [comment]
Ok the quick fix is working, which is all I need for now. Thank you!
