### ISSUE TITLE
Adding a scheme

### ISSUE THREAD

**Issue by fvepwc** [OnroerendErfgoed/atramhasis#421]
Is it possible to add a scheme?
In the admin pane of Atramhasis, I can edit an existing scheme or add concepts/collections but I don't see a way to add a scheme.
Is there a way to do this? Perhaps directly in the database? I don't know exactly how to access the underlying database so I cannot check myself.

Thanks,
Frederik

**Comment by koenedaele** [comment]
Yes, it is possible. But you do have to do some configuration stuff. See http://atramhasis.readthedocs.io/en/latest/customisation.html#creating-your-own-project for the full instructions.

Basically, what you need to do:
 - Add a record in the database for the scheme itself. For sqlite3 you should be able to do this with sqlite3 atramhasis_demo.sqlite (or whatever you called it). I believe there are also GUI tools for handling sqlite database, but you'de have to search for those.
- Edit atramhasis_demo/skos/__init__.py to tell Atramhasis how to handle this conceptscheme. In it's simplest form you need to configure an id to be used in the application's URL's. And a conceptscheme_id that connects the provider with the database. But you'll probably want to a a UriGenerator as well to control the kinds of URI that get generated.

**Comment by koenedaele** [comment]
Took a while, but we did add this in #724
