### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#423]
In 0.6.2 there were some problems with sorting a collection of concepts in the templates ( #420 ). They were fixed in certain places by only sorting on id. For the search result page, the sorting was delegated to the provider.

This is not ideal, since:
- The relations of a concept are now sorted by id, not a label. But it looks like in the old version it didn't work anyway.
- Sorting of a collection of concepts on label or sortlabel will always be to complicated to be done in a simple Jinja template. Best option might be to create a custom search filter.
- Search results are now always sorted by label. Ideally, the user could choose the sort order. Possible complication here would be sorting by SortLabel. This can be used to sort eg. Dateringen chronologically, but this might seem confusing for a user.

I'm reducing this issue to the sorting of relations in a template. See eg. https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/174, the narrower terms are sorted by id, not by label or some other meaningful attribute (for a user).

This means fixing the jinja2 macro render_relaties_lijst so it doesn't sort on the attribute id, but on the function concept._sortkey(key='sortlabel', language=current_language_of_user). I don't think this is possible with the standard jinja2 sort filter, so this would require writing a custom sort filter for sorting relations of concepts or collections.

**Comment by koenedaele** [comment]
I'm reducing this issue to the sorting of relations in a template. See eg. https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/174, the narrower terms are sorted by id, not by label or some other meaningful attribute (for a user).

**Comment by Wim-De-Clercq** [comment]
Kweet niet of dit de moeite is om epic van te maken en op te splitsen BE/FE, Ik denk dat beide partijen wel in staat zijn om dit te doen.

```
def label_sort(concepts, language='any'):
    if not concepts:
        return []
    return sorted(
        concepts, key=lambda concept: concept._sortkey(key='sortlabel',
                                                       language=language)
    )
```
`<register in settings>`
```
{% for concept in concepten|label_sort(language="user-lang") %}
```

Ik weet wel niet echt waar de taal vandaan kan komen.

**Comment by Wim-De-Clercq** [comment]
> I'm not sure where the user's language could come from though

I found this in other code perhaps: `request.locale_name`

**Comment by koenedaele** [comment]
Language should generally be:
`language = self.request.params.get('language', self.request.locale_name)`

Allowing the end user to override the languuage through a query string parameter.

**Comment by JonasGe** [comment]
Should this be possible for every type of view or only non-html (csv and json)?

In my opinion, allowing a custom request parameter to set the locale for html views would nullify the purpose of the locale cookie.

**Comment by koenedaele** [comment]
I see that the rest of the HTML interface uses the request.locale_name as well. It's only the services in pyramid_skosprovider that allow the language parameter. Also, the request.locale_name calculation allows for a GET parameter _LOCALE_ to override the cookie if needed, so it's already possible. Might have to think about changing the service as well or not.

**Comment by koenedaele** [comment]
Just noticed that locale_name can be subtly different from the language tags we're using (ie. en_US vs. en-US), so there's probably some edge cases errors out there somewhere.
