### ISSUE TITLE
add some screenshots

### ISSUE THREAD

**Issue by VladimirAlexiev** [OnroerendErfgoed/atramhasis#440]
Could you kindly add some shots to http://atramhasis.readthedocs.io/ or https://github.com/OnroerendErfgoed/atramhasis/blob/master/README.rst?
These are very useful to someone who wants to decide whether to use the tool.
Thanks!

**Comment by koenedaele** [comment]
Sure. Any suggestions on what you would like to see?

**Comment by VladimirAlexiev** [comment]
edit a concept, concept hierarchy, search/autocomplete...
Dunno what features it has :-)

**Comment by koenedaele** [comment]
You can see a reskinned version in action at https://thesaurus.onroerenderfgoed.be/, but that's only the public front.

Easiest way to test the whole thing, is to use the docker democontainer: http://onroerenderfgoed.github.io/posts/2018/atramhasis-docker/

But I'll add a few screenshots to the docs as well.
