### ISSUE TITLE
Import and export script use different file formats

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/atramhasis#452]
At this point we can export data to ttl and rdf file formats. The rdf export gives us a rdf-xml file (rdf extension). The export to turtle gives us a ttl extension. Both extensions are not accepted by the import script. 

Accepted extensions by the import script:
 ```
   'RDF': {
        'extensions': ['.html', '.hturtle', '.mdata', '.microdata', '.n3', '.nquads', '.nt', '.rdfa', '.rdfa1.0',
                       '.rdfa1.1', '.trix', '.turtle', '.xml'],
        'file_to_provider': file_to_rdf_provider
    },
    'CSV': {
        'extensions': ['.csv'],
        'file_to_provider': file_to_csv_provider
    },
    'JSON': {
        'extensions': ['.json'],
        'file_to_provider': file_to_json_provider
    }
```

It would be more convenient if both import and export would use the same file formats.

**Comment by koenedaele** [comment]
Fixed by #476. Export formats where left as-is (rdf = rdf/xml, ttl = turtle), import formats were update to allow all formats rdflib is capable of handling
