### ISSUE TITLE
Atramhasis 0.6.5 AND 0.6.6 is an incomplete package

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#462]
The 0.6.5 release does not includes certain folders such as the src folder, making it impossible to get a full version running. It needs to be repackaged using the following command:

```bash
$ python setup.py prepare sdist bdist_wheel
```

**Comment by koenedaele** [comment]
This problem was discovered in #461

**Comment by koenedaele** [comment]
We'll release a corrected 0.6.6 version

**Comment by cedrikv** [comment]
fixed in 0.6.7
