### ISSUE TITLE
parsing error turtle import_file script

### ISSUE THREAD

**Issue by bertvannuffelen** [OnroerendErfgoed/atramhasis#476]
The file is valid turtle syntax: https://github.com/Informatievlaanderen/codelijsten/blob/master/adressenregister/adresstatus.ttl

but when using it to import via file_import (first changing the file extension to turtle) it uses the sax RDF/XML parser instead of the turtle parser.

kr,

Bert

**Comment by koenedaele** [comment]
Seems like rdflib needs to be told exactly what type of file a file is and is not very good at guessing what it could be. See https://rdflib.readthedocs.io/en/3.4.0/using_graphs.html#the-graph-class. From reading the code, not specifying the format only makes sense for files fetched over the web.

**Comment by koenedaele** [comment]
Also, see #452 

Looks like we'll need to handle this differently.

**Comment by koenedaele** [comment]
Ah, just noticed that we do try to guess the RDF format in the import_file command. Something must nog be working there.

**Comment by koenedaele** [comment]
Not really sure what's going on here, I managed to import a turtle file by naming it .ttl and patching the import_file script in my virtualenv and adding ttl to the list of file extensions that map to the RDFProvider.
