### ISSUE TITLE
We want to be able to search concepts that match an external URI

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#498]
We want to be able to search for concepts that match a certain external URI. I should be able to search https://thesaurus.onroerenderfgoed.be for concepts that match http://vocab.getty.edu/aat/300005241 and find https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/1273

**Comment by cedrikv** [comment]
![image](https://user-images.githubusercontent.com/1849458/89628649-e5325400-d89c-11ea-8037-3726f045a317.png)

Is this ok for the UI @koenedaele ? Placeholder makes it a bit crowded, but gives the users a good idea about the purpose. I can change it into a tooltip on the label too.
