### ISSUE TITLE
Update to match searches for latest pyramid_skosprovider

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#499]
Make sure searches with match and match_type (koenedaele/pyramid_skosprovider#68) from the latest pyramid_skosprovider work in atramhasis as well.

I should be able to call https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES?match=http://vocab.getty.edu/aat/300005241 for concepts that match http://vocab.getty.edu/aat/300005241 and find https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/1273

From reading the code this is probably as simple as updating to the latest pyramid_skosprovider for the REST service.

The public HTML endpoint (https://github.com/OnroerendErfgoed/atramhasis/blob/develop/atramhasis/views/views.py#L160) will require more work. We want the same link to work in a browser and provide the same results, although updating the UI is out of scope at the moment.

**Comment by Wim-De-Clercq** [comment]
> I should be able to call https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES?match=http://vocab.getty.edu/aat/300005241 for concepts that match http://vocab.getty.edu/aat/300005241 and find https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/1273

Should it not be https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c?match=http://vocab.getty.edu/aat/300005241 with the extra `/c` to search concepts?

**Comment by koenedaele** [comment]
> > I should be able to call https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES?match=http://vocab.getty.edu/aat/300005241 for concepts that match http://vocab.getty.edu/aat/300005241 and find https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/1273
> 
> Should it not be https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c?match=http://vocab.getty.edu/aat/300005241 with the extra `/c` to search concepts?

Yep, my bad.

**Comment by Wim-De-Clercq** [comment]
Ik had het serieus overschat denk ik, nu ik het allemaal nog eens bekijk.

Dit is ook blocked op release van pyramid_skosprovider 0.9.0, kan lokaal wel testen via git pip installs.
