### ISSUE TITLE
Improved SEO

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#500]
Improve Atramhasis SEO

**Comment by verdugvi** [comment]
Hoort mss niet hier, maar nu komen er in google ook resultaten van ontwikkelomgeving. Is dat de bedoeling? Zoeken werkt wel goed :)

![image.png](https://images.zenhubusercontent.com/5c6fd54e4b37af06f833eef5/80467abe-fbe2-43a3-8bf2-4117ba9621de)

**Comment by koenedaele** [comment]
Bugger, nee dat hoort inderdaad niet. Nu, veel zal dat niet met de bovenstaande tickets te maken hebben. De sitemap is nog leeg en zo snel gaat dat allemaal niet bij Google.

Beste oplossing is een robots.txt voorzien om dev en test buiten de index te houden. Kunnen we meteen ook in verwijzen naar de sitemap.

**Comment by cedrikv** [comment]
zie https://github.com/OnroerendErfgoed/plannen/pull/738/files
