### ISSUE TITLE
Add Filter by match to admin interface

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#501]
Add filtering by match to the admin interface. I want to be able to enter the URI of a concept (does not have to be validated by an external provider) and search for it using the `?match=URI` parameter.

**Comment by verdugvi** [comment]
Ik krijg hier precies geen resultaten, ook niet als ik de URI aanpas naar https://dev-id...
![image.png](https://images.zenhubusercontent.com/5c6fd54e4b37af06f833eef5/4d042371-5ee1-40f0-a1f2-fd332628c422)

**Comment by koenedaele** [comment]
Dat gaat over matches met externe thesauri, zoek bv. eens naar http://vocab.getty.edu/aat/300007466 in het schema erfgoedtypes.

**Comment by verdugvi** [comment]
Aha! Ja dan krijg ik inderdaad het correcte resultaat.
