### ISSUE TITLE
We want concept inheritance to work

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#502]
In 0.6.0, there's a problem with expanding a concept that has a narrower collection (a guide term or node label) that contains other concepts. This needs to be fixed. In the new skosprovider, a collection has an attribute infer_concept_relations. If true, all concepts in a collection are narrower concepts of that collection's broader concept. If false, not. Default is true.

Implementing this, we have a few options:
- Leave the interface as it currently is and just always use the default True value, thus always choosing for inheritance.
- Copy the skosprovider data model and add a yes/no field.
- Don't copy the datamodel, but just create collection subtypes and use those. Eg, call it GuideTerm as Getty vocab does and use thread-though like in http://vocab.getty.edu/doc/#Subject_Hierarchy

Suggested course of action:
- Copy the skosprovider data model and add a yes/no field. Since this only affects search, we don't show this information in the public interface.

**Comment by koenedaele** [comment]
Similar to #136

**Comment by cedrikv** [comment]
@koenedaele whats a good name/label for this field?
"Inheritance"?
