### ISSUE TITLE
Requirements updaten

### ISSUE THREAD

**Issue by vandaean** [OnroerendErfgoed/atramhasis#505]
De requirements uit athramhasis-requirements.txt worden niet gebruikt. Ik heb ze nu allemaal toegevoegd aan requirements.txt om te kunnen deployen.

Verder kijken om de requirements te updaten en athramasis-requirements te verwijderen.

**Comment by koenedaele** [comment]
Ik denk dat je een thesaurus ticket hebt aangemaakt in de Atramhasis repo. Deze is voor problemen met de Atramhasis basis build, niet met de thesaurus implementatie.
