### ISSUE TITLE
Add a Twitter Card

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#530]
Add a twitter card of type summary for each concept and conceptscheme so I can properly tweet a concept.

See https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

Values:
* twitter:card : static and set to `summary`
* twitter:site : configurable through production.ini, don't add if not set. should be @vioe for us when we configure this for https://thesaurus.onroerenderfgoed.be
* twitter:title : prefLabel of the concept or conceptscheme
* twitter:description : scopeNote of the concept or conceptscheme if available

**Comment by JonasGe** [comment]
@koenedaele Do you want to add all notes attached to a concept or only the first note (which has `notetype_id` `scopenote` but can also contains a `definition` when `scopenote` is not available) to the description?

**Comment by koenedaele** [comment]
I think the twitter card only supports one description, so the first note.
