### ISSUE TITLE
Generate a one-page tree for a conceptscheme

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#532]
Generate a tree visualistion using nested lists. The top level of the hierachy can be found by calling provider.get_top_display (NOT get_top_concepts). For each of those top concepts or collections, provider.get_children_display should be called recursively until there are no deeper concepts or collections. See OnroerendErfgoed/thesaurus#59 for possible visualisations.

**Comment by JonasGe** [comment]
@cedrikv @astridvanhumbeeck 

![image](https://user-images.githubusercontent.com/2376436/86954387-2c221200-c156-11ea-92bc-a0da62831bf8.png)

Als het om af te drukken is, laat ik dan de header, footer, grijze achtergrond, ... weg?

**Comment by astridvanhumbeeck** [comment]
> Als het om af te drukken is, laat ik dan de header, footer, grijze achtergrond, ... weg?

Ja zeker de achtergrond liefst wit. Header en footer mag ook weg als dat niet teveel moeite is.
