### ISSUE TITLE
Provide a link to a printable tree

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#533]
Provide a link from a conceptscheme overview page to the printable tree page. So, eg. from  https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES to https://thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/tree.

When looking at the conceptscheme page I don't really see a quick and easy solution for the link, so perhaps @verdugvi needs to think about this for a minute.

**Comment by verdugvi** [comment]
Maybe as an extra download option 'HTML'?
It's probably not really a download, but the existing option 'Full N3/Turtle' doesn't download in my browser (Chrome) either. And the purpose of the printable tree is to extract it, so it might makes some sense?

If that's really a problem the label 'Download' could be changed to 'Export'?

**Comment by JonasGe** [comment]
FYI: The route has been changed to /treeprint to avoid conflicts with how the inventaris ingests the /tree endpoint (expects json but is not enforced so providing a text/html alternative would cause a conflict)
