### ISSUE TITLE
Application errors out generating a tree when no label defined for a concept

### ISSUE THREAD

**Issue by Jefwillems** [OnroerendErfgoed/atramhasis#540]
When trying to load a conceptscheme tree, and there is 1 concept missing a label, the application encounters an unhandled error and returns status code 500. I narrowed the problem down to the next 2 lines. The error gets thrown when child.label(locale) returns None.

https://github.com/OnroerendErfgoed/atramhasis/blob/0113d43cb38d5584ed9ae864350a2fc58ca87c5f/atramhasis/views/views.py#L271

https://github.com/OnroerendErfgoed/atramhasis/blob/0113d43cb38d5584ed9ae864350a2fc58ca87c5f/atramhasis/views/views.py#L286

A good solution 'imo' would be passing 'None' as a label, or handling this issue in data validation when creating the concept.

**Comment by koenedaele** [comment]
Not a fan of turning None into a string. In this case it seem like this code should be updated to be more defensive and handle a concept not having any labels.

I assume we allow not having a label for certain legacy data and weird stuff. Especially with conceptschemes.

**Comment by koenedaele** [comment]
@cedrikv I'll leave it up to you to assign to a developer. Solution should be fixing lines 286, 271 and 272 in that file.
