### ISSUE TITLE
Exceptions nakijken ikv python3

### ISSUE THREAD

**Issue by JonasGe** [OnroerendErfgoed/atramhasis#566]
Nakijken of de velden in de exceptions bestaan (bvb `exc.message`) en indien nodig aanpassen in `exception_views.py`.

**Comment by Wim-De-Clercq** [comment]
In `validators.py` is er een om op te kuisen denk ik.

**Comment by vancamti** [comment]
na wat uitzoekwerk geen code changes vereist
