### ISSUE TITLE
Tree component no longer loading

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#585]
The component that renders the foldable tree no longer functions. It does a GET request to `/conceptschemes/EVENTTYPE/tree?language=en` with an Accept: application/json header, but gets the HTML version, not the JSON version of the data.

Not sure what's happening since the routes configuration looks allright:

```
config.add_route('scheme_tree_html', pattern='/conceptschemes/{scheme_id}/tree', accept='text/html')
config.add_route('scheme_tree', pattern='/conceptschemes/{scheme_id}/tree', accept='application/json')
```

**Comment by JonasGe** [comment]
This seems to be working on the develop branch:

Accept: application/json
![image](https://user-images.githubusercontent.com/2376436/88269560-8e415200-ccd4-11ea-93db-89e1a103c706.png)

Accept: */*
![image](https://user-images.githubusercontent.com/2376436/88269625-a7e29980-ccd4-11ea-9723-8c8c411eb73f.png)

**Comment by koenedaele** [comment]
Running the develop branch as well.

**Comment by koenedaele** [comment]
Currently I always get the "first" route as defined in routes.py, no matter what the accept header.

**Comment by koenedaele** [comment]
Hmm, using a REST client (insomnia), everything works as it should. Problems only happen in my browser (both FF and Chromium).

**Comment by koenedaele** [comment]
Browsers send Accept: "application/json,*/*" (I want JSON and if you don't have that anything else will do). Using that in a REST client I still get the HTML version. So, the accept header handling isn't what it should be?

**Comment by Wim-De-Clercq** [comment]
The html route comes first in the code, so if any will do, then that's the one pyramid will take.
Which is good because you want the html if you just browse to `/tree`. If you were to put the json one first, a browser will get that when people browse to `/tree` because browsers will always add `*/*` as fallback in the Accept header.

If the component that handles the tree can only handle json, it should request only json imo.

**Comment by JonasGe** [comment]
I misread the question, I was checking the endpoint and not the tree component.

The problem with the tree component itself is that d3 doesn't send an accept header by default.

I adapted the tree.jinja2 code to send an Accept: application/json header with the d3 request and now it seems to work.

I'll push the code.
