### ISSUE TITLE
Document how to generate a sitemap

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#616]
I tried generating a sitemap for the demo with the command: sitemap_generator development.ini

Produced the following output:

```
(atdemo) koen@lilith:~/Projecten/python/skos/atdemo$ sitemap_generator development.ini
[WARNING]The target sitemap directory (/home/koen/.virtualenvs/atdemo/lib/python3.6/site-packages/atramhasis/static/_sitemaps) is not empty.
Existing sitemaps may get overridden. But the sitemap index file will contain all sitemaps in the folder, even old ones that are no longer needed. Consider deleting the contents of the folder first.
Press [Enter] to continue.^CTraceback (most recent call last):
  File "/home/koen/.virtualenvs/atdemo/bin/sitemap_generator", line 33, in <module>
    sys.exit(load_entry_point('atramhasis', 'console_scripts', 'sitemap_generator')())
  File "/home/koen/.virtualenvs/atdemo/lib/python3.6/site-packages/atramhasis/scripts/sitemap_generator.py", line 159, in main
    input("Press [Enter] to continue.")
```

I'm not sure how this is supposed to work and the docs don't provide information.

**Comment by koenedaele** [comment]
Docs are ok, but I just noticed the files get created in the .virtualenv, which doesn't seem to be the point? Shouldn't this be relative to the application generating the sitemap? Like how the generate_ldf_config file works?

**Comment by cedrikv** [comment]
related discussion: https://github.com/OnroerendErfgoed/besluiten/issues/481

**Comment by cedrikv** [comment]
it is the expected behavior that the sitemaps are created in the virtualenv on your server (I checked on our production server with other projects). Pyramid routing takes care of everything.
