### ISSUE TITLE
As a user I want te be able to download a Concept or Conceptscheme as JSON-LD

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#623]
Pyramid skosprovider supports JSON-LD since 0.9.0, but Atramhasis overrides some of the pyramid routes, rendering the implementation non-functional or messing the audit function up. Also, since pyramid_skosprovider a hyperlink with a jsonld exists, making it possible for a user to download JSON-LD from a browser.

**Comment by verdugvi** [comment]
@roefem meldt dat download knop voor concepten niet doorkomt
