### ISSUE TITLE
Op de dev omgeving zijn er nog links naar heritagedata

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#634]
Ik dacht dat we de heritagedata thesauri verwijderd hadden. Maar in elk geval op dev is er nog een link aanwezig bij https://dev-thesaurus.onroerenderfgoed.be/conceptschemes/ERFGOEDTYPES/c/1005

De provider is denk ik al weg, maar de URI bestaat nog. Maar dit geeft vreemde resultaten. Oplossing is denk ik om gewoon in de databanken alle verwijzingen naar heritagedata.org te verwijderen.

**Comment by cedrikv** [comment]
opgelsot met 'delete from match where uri like 'http://heritagedata.org/%''
