### ISSUE TITLE
Upgrade naar Pyramid 2.0

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/atramhasis#648]

**Comment by koenedaele** [comment]
Don't forgot to check the docs to see if they become invalid because of these changes.

**Comment by Wim-De-Clercq** [comment]
Ja, dit is meer dan gedacht. Want gans het scaffolding gebeuren was al deprecated sinds 1.8. En sinds 2.0 eruit.
> Note: As of Pyramid 1.8, this command is deprecated. Use a specific cookiecutter instead: https://github.com/Pylons/?q=cookiecutter
