### ISSUE TITLE
Integration with LDF is out of date

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#687]
The docs at https://atramhasis.readthedocs.io/en/latest/development.html#running-a-linked-data-fragments-server still suggest installing ldf-server, while this has been deprecated and replaced by @ldf-server. See https://github.com/LinkedDataFragments/Server.js/wiki/Release-3.0.0#migration-from-2xx

The docs need to be updated, but the generated config file is also out of date and should be replaced with a JSON-LD compatible version

**Comment by goessebr** [comment]
[config-new.txt](https://github.com/OnroerendErfgoed/atramhasis/files/8868599/config-new.txt)
[config-old.txt](https://github.com/OnroerendErfgoed/atramhasis/files/8868600/config-old.txt)

**Comment by goessebr** [comment]
Acceptance criteria
- The script generates an LDF config file in the new format
- docs are updated
