### ISSUE TITLE
Docs should be updated for creating a demo site

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#699]
Currently the docs at https://atramhasis.readthedocs.io/en/latest/demo.html are from the old (0.7.0) version and don't mention the cookiecutter templates.

**Comment by goessebr** [comment]
Hi @koenedaele 

I will drop the Docker and Heroku documentation. Is that ok or do you have a strong desire to keep Docker and Heroku on board? The cookiecutter demo is imo a solid option for all users and it's easier to keep only 1 option up to date instead of a few alternatives.

**Comment by koenedaele** [comment]
Dropping the Heroku docs is fine. I think there are more fans of the docker demo, but if it's too much hassle to maintain, I don't mind dropping it.
