### ISSUE TITLE
Upgrade jinja2

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/atramhasis#702]
Since 3.1.0 It is not longer possible to include the `with` extension, this extension is now built-in. Trying to include this extension will prevent the application from starting up

More info: The https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0 and https://github.com/pallets/jinja/pull/1544/files
> WithExtension and AutoEscapeExtension are built-in now.

I'm not sure we are using with in this application anyway, but the line` jinja2.ext.with_` needs to be removed out of the ini file(s).

**Comment by milvala** [comment]
Hi @goessebr 

I just wanted to let you know that I still ran into this error today when trying to run the demo with cookiecutter. I don't know why exactly, but it seems that something is not up to date yet :smile: 

Removing `jinja2.ext.with_` from the `development.ini` indeed solved the error :+1:

**Comment by goessebr** [comment]
Hi @milvala 

It is correct that the project is not yet up to date. Some things in the https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter repo need more testing so the develop branch is not yet merged with master

This is a atramhasis_demo_cookiecutter problem, rather then an atramhasis problem. You can try to follow the steps at the develop branch https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter/tree/develop for a more up to date version of the cookiecutter repo.
This line is important at step 1 `cookiecutter gh:OnroerendErfgoed/atramhasis_demo_cookiecutter --checkout develop `, this way you will start from a beta release of the renewed template
