### ISSUE TITLE
Startup error with Atramhasis demo when surfing to http://localhost:6543/admin

### ISSUE THREAD

**Issue by milvala** [OnroerendErfgoed/atramhasis#713]
Hi

After installing the Atramhasis demo with cookiecutter and trying to reach http://localhost:6543/admin (to test the editing of thesauri), I ran into the following error message, pasted below:

```
Startup error: 

There was a problem connecting to the backend services, the application cannot be started.
```

Any idea what's going on?

Thanks in advance!

**Comment by milvala** [comment]
The Pyramid DebugToolbar seems to signal an error with `GET /conceptschemes`:

`Could not guess RDF format for <rdflib.parser.StringInputSource object at 0x7f35a2204fa0> from file extension so tried Turtle but failed.You can explicitly specify format using the format argument.`

**Comment by goessebr** [comment]
I'm aware of what is going on and this will be fixed in the near future via https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter/issues/10. Might be a couple of weeks but it is on the todo list.

For now you can comment 2 lines in the skos folder:
```
#    registry.register_provider(aat)
#    registry.register_provider(tgn)
```
