### ISSUE TITLE
import_data.py: NameError: name 'Note' is not defined

### ISSUE THREAD

**Issue by mielvds** [OnroerendErfgoed/atramhasis#721]
I'm getting a `NameError` on `Note`  in https://github.com/OnroerendErfgoed/atramhasis/blob/develop/atramhasis/scripts/import_file.py#L209 when importing [this Turtle skos file](https://github.com/i-Learn-SKOS/common-conceptschemes/blob/main/common/schemes/onderwijsstructuur-final.skos.ttl). Shouldn't the `Note` and `Source` function be imported somewhere or is something else going on?

**Comment by koenedaele** [comment]
Looks like a bug. Don't think this script is covered by unit tests.

I do see that the skos file contains SKOSXL statements, which we currently don't support. So, any SKOSXL statements will be ignored.
