### ISSUE TITLE
Creating providers - frontend

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#745]

**Comment by cedrikv** [comment]
@koenedaele What input fields do we want to provide for creating a provider? And do we need required fields/validation/..?

**Comment by cedrikv** [comment]
i was lanning to reuse the languages UI, if thats ok:
![image](https://user-images.githubusercontent.com/1849458/236237536-f47bba53-128f-4b77-8576-6a03b849271e.png)

**Comment by koenedaele** [comment]
Ok with using the languages UI.

Fields (based on #744 and #812 ):
 - id (string): not required on creating (default's to conceptscheme id if not set), read from GET on update (and immutable)
 - conceptscheme_uri (string): required on create to create the conceptscheme, not available on update (since the link with the CS is already in the DB and the conceptscheme is editable through the UI already)
 - uri_pattern (string): required
 - default_language (string): not required, one language from the list of available languages
 - force_display_language (string): not required, one language from the list of available languages
 - id_generation_strategy (string): not required on create (but defaults to NUMERIC if not set), one of NUMERIC, MANUAL or GUID
 - subject (list of unique strings): not required. Right now only 'hidden' does something. We could allow other, non-predefined subjects but they don't do anything. So it's basically either ['hidden'] or []
 - expand_strategy (string): not required on create, will default to RECURSE, one of 'RECURSE' or 'VISIT'

**Comment by cedrikv** [comment]
also @koenedaele : do we want to exclude all the external providers from this dialog?

**Comment by koenedaele** [comment]
Either exclude them or make them appear in the grid but uneditable.

**Comment by cedrikv** [comment]
this is the current ui:
![image](https://github.com/OnroerendErfgoed/atramhasis/assets/1849458/2bc58138-8a1d-4cfd-9c73-a29113cfbc9c)
![image](https://github.com/OnroerendErfgoed/atramhasis/assets/1849458/2f736f7b-5618-4e6c-93bf-f75861d20c25)
![image](https://github.com/OnroerendErfgoed/atramhasis/assets/1849458/a5da58a5-98a8-48ac-ab70-62d252b8c397)
