### ISSUE TITLE
Wheel still seems to support py2

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#752]
In version 1.3.0 the wheel is named atramhasis-1.3.0-py2.py3-none-any.whl (https://pypi.org/project/atramhasis/1.3.0/#files). This seems to indicate we still support Python 2, while I don't think we do. I think this is because of the universal flag in https://github.com/OnroerendErfgoed/atramhasis/blob/develop/setup.cfg ? 

Not sure if any of this matters a lot, but if possible I'd stop the universal wheel.

**Comment by Wim-De-Clercq** [comment]
Can confirm, py2 in the name is caused by the universal flag.
