### ISSUE TITLE
Can't install development version

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/atramhasis#755]
In openjournals/joss-reviews#5040 @gaurav has noticed that:

I got stuck pretty early on in the review process because the [Atramhasis repository](https://github.com/OnroerendErfgoed/atramhasis/) doesn't have installation instructions. I tried following the installation instructions at [your readthedocs.io page](https://atramhasis.readthedocs.io/en/latest/development.html#general-installation) page, but running initialize_atramhasis_db development.ini resulted in the following error:

`
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 2.0.1 (/Users/gaurav/Development/open-source/atramhasis/venv/lib/python3.9/site-packages), Requirement.parse('MarkupSafe>=2.1.1'), {'werkzeug'})
`

Normally things should work for Python 3.9.

**Comment by Wim-De-Clercq** [comment]
That's https://github.com/OnroerendErfgoed/atramhasis/issues/747 
Because we don't support the latest jinja2, we also do not support the latest markupsafe.

**Comment by Wim-De-Clercq** [comment]
Extra things i'll fix here:

- admin interface having css issues
- there's an unnecessary __init__.py in the root.
