### ISSUE TITLE
Unclear distinction in the demo between the languages "Flemish" and "Dutch, Flemish, Belgium"

### ISSUE THREAD

**Issue by SvenLieber** [OnroerendErfgoed/atramhasis#760]
A tiny detail I noticed while testing the demo for https://github.com/openjournals/joss-reviews/issues/5040

### Description 

In the following dialog a user might get confused when being offered Flemish twice.

![image](https://user-images.githubusercontent.com/3501171/213426186-7a2bac8d-13c1-4363-80b0-303c0aba7e68.png)

After saving in the UI (and also in a SKOS RDF export), one of the two different Flemish labels has the language code `vls` which is used for West Flemish (according to [Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)), but this was not clear from the UI in the dialog.

However, this is probably negligible as displayed languages can be changed from the UI (in which also new languages can be added) and this is just a demo environment with some prefilled languages.

### Steps to reproduce

1. Running the demo using cookiecutter
2. Opening the admin interface
3. Editing an existing concept

**Comment by koenedaele** [comment]
Yes, it is confusing. I probably should have picked another example language, but I was born in West-Flanders ;-)

The languages get validated against the IANA language registry and that's also confusing:
```
[
  {
                "Type": "language",
                "Subtag": "vls",
                "Description": [
                        "Vlaams"
                ],
                "Added": "2009-07-29"
        },
       {
                "Type": "language",
                "Subtag": "nl",
                "Description": [
                        "Dutch",
                        "Flemish"
                ],
                "Added": "2005-10-16",
                "Suppress-Script": "Latn"
        },
]
```

It's rather weird that vls is Vlaams, but nl is Flemish.

I'm also not sure if IANA vls is actually West-Flemish or what linguists would call Flemish (with sub languages West-Flemish, East-Flemish, French-Flemish and Zeelandic Flemish).

Anyway, it might be a good idea to change the label of vls in the demo to Vlaams, that way it's consistent with the official IANA declaration and it is what you would get if you imported a rdf language string such as "Toekter"@vls. But still confusing. So, maybe it would actually be best to update those dialogs (adding labels and notes) to show not just the Language label but also the code. We normally don't show identifiers but in this case the identifiers are pretty well known strings so it shouldn't be a problem.
