### ISSUE TITLE
Upgrade naar SQLAlchemy 2.0.0

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/atramhasis#768]
Zie ook https://github.com/OnroerendErfgoed/bredero_dossierdata/issues/136

**Comment by koenedaele** [comment]
Skosprovider_sqlalchemy 2.0.0 was made compatible with SQLAlchemy 1.4 (forwards compatible with SQLA 2). Atramhasis 2.0.0 will follow Skosprovider_SQLA 2.0.0. A later version of Atramhasis will drop support for SQLA 1.4
