### ISSUE TITLE
Integrate Cookiecutter Projects into Atramhasis for Improved Maintainability and Centralization

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/atramhasis#876]
We have 2 cookiecutter projects that create an Atramhasis project:

[Atramhasis Demo Cookiecutter](https://github.com/OnroerendErfgoed/atramhasis_demo_cookiecutter) to create a demo application.
[Atramhasis Scaffold Cookiecutter](https://github.com/OnroerendErfgoed/atramhasis_scaffold_cookiecutter) to create a clean new application.
We could integrate these cookiecutter projects into Atramhasis.

Integrating these projects will improve the maintainability of the code and centralize the project along with the cookiecutter projects. This will provide a more cohesive development experience and ensure that all components are in sync.

Any thoughts about this?

Useful links:
https://cookiecutter.readthedocs.io/en/stable/cli_options.html#cmdoption-cookiecutter-directory

**Comment by Wim-De-Clercq** [comment]
After this is fully released. We should probably consider archiving the cookiecutter repositories.
![image](https://github.com/OnroerendErfgoed/atramhasis/assets/4599667/762b77c8-a5f8-4040-bd98-ffb115834ba3)

Or deleting, I suppose, but archiving may be nicer for people who have the links and for older tags and branches which refer to it.

**Comment by goessebr** [comment]
I will archive the old cookiecutter repositories once the new Atramhasis release is available.
