### ISSUE TITLE
Conceptschemes are 'reflected' on the homepage

### ISSUE THREAD

**Issue by mielvds** [OnroerendErfgoed/atramhasis#892]
When you open atramhasis, there's a gray reflection/shadow of the conceptschemes on the homepage. See the schemes at the end in the attached screenshot.

![Screenshot 2024-07-09 at 14 37 08](https://github.com/OnroerendErfgoed/atramhasis/assets/1032980/37649d53-98c3-4df9-aad1-35c57b985155)

When the page is refreshed, the list changes.

**Comment by koenedaele** [comment]
I assume you mean the four schemes at the bottom? 

These 4 are the focal conceptschemes mentioned in https://atramhasis.readthedocs.io/en/latest/customisation.html#appearance Normally they will list the three most visited concepts for those conceptschemes. See https://thesaurus.onroerenderfgoed.be/

![image](https://github.com/OnroerendErfgoed/atramhasis/assets/676018/9e7201d2-68c7-41ee-a4b6-2f7eb29a29a8)

I assume you haven't configured any, so Atramhasis just picks 4 random schemes on page load.

Before it wasn't possible to configure providers/schemes through the UI, so it made sense that the focal conceptschemes could only be set through the ini file. Now, it might be better to have this editable in the UI as well.

**Comment by mielvds** [comment]
ah whops it's a feature, not a bug ;) I was confused because there's nothing clickable in there. Maybe they can be hidden if there are no most visited concepts, but we can do that when customizing the UI.

**Comment by koenedaele** [comment]
I think we might cache it fairly agressively, so it might take a while for it to contain some useful data.
