### ISSUE TITLE
Manual ID text box not writable

### ISSUE THREAD

**Issue by DavideLicheri** [OnroerendErfgoed/atramhasis#902]
Today I was able to update my atramhasis server to the 2.1.0 version.
With this new release it's impossible to insert any value in the text box for the manual ID in the +Add popup for a new concept/collection, 'cause no chance to have a cursor inside...

Thanks for your help!
davide

**Comment by goessebr** [comment]
Hi @cedrikv,

I could use some assistance with this issue.

The field in question was added in version 2.0.0, as shown in this code snippet: [link](https://github.com/OnroerendErfgoed/atramhasis/blame/c56bb61090078f975d16c148dd7da0f960781de6/atramhasis/static/admin/src/app/ui/dialogs/templates/ManageConceptDialog.html#L18). Currently, the field is disabled at all times.

Based on the code in [crud.py](https://github.com/OnroerendErfgoed/atramhasis/blob/40dbb1f62373806c9d9b3a55dbb0e57d43e210b8/atramhasis/views/crud.py#L178-L180), it appears that the provider's metadata should determine whether this field can accept manual input.

For additional context, please refer to these related issues: [#732](https://github.com/OnroerendErfgoed/atramhasis/issues/732) and [#740](https://github.com/OnroerendErfgoed/atramhasis/issues/740).

Could you please take a look at this?

**Comment by goessebr** [comment]
Oh wait, I overlooked [this line of code](https://github.com/OnroerendErfgoed/atramhasis/blob/60c5867eddf1e6cf684a8a97035ee9ec0659d175/atramhasis/static/admin/src/app/ui/dialogs/ManageConceptDialog.js#L137). Dojo code isn't my strong suit.

@DavideLicheri, could you check if your provider uses a manual ID generating strategy? You can do this by opening the dialog to update the provider.
![image](https://github.com/user-attachments/assets/1daf7c55-b78c-4f9d-8710-5aab251f51b1)


You might want to hard refresh your browser if you recently changed this setting.

Additionally, I noticed that the dialog to create a new concept retains the IDs of previously opened concepts, which seems to be a bug.

**Comment by DavideLicheri** [comment]
ciao Bram,
I've checked my provider. It is (as usual for me) a provider with MANUAL id generating strategy... 
The problem persist after a restart of the server.

...and no one ID retained opening the dialog to create a new concept/collection.

**Comment by goessebr** [comment]
Hi @DavideLicheri 

I had to perform a hard refresh of the browser (Ctrl-F5) while this window was open.
![image](https://github.com/user-attachments/assets/43f9d65d-516c-4fb0-8b09-09b1db0bb7e7)

Reopening the window allowed me to insert my manual IDs, although I did change the ID generation strategy from numeric to manual.

Do I understand correctly that you updated from version 2.0.0 to 2.1.0 and were able to insert manual IDs while working with version 2.0.0?

**Comment by DavideLicheri** [comment]
“Reopening the window allowed me to insert my manual IDs”

I will try 

“ updated from version 2.0.0 to 2.1.0”

Yes, with pip install atramhasis==2.1.0

“ were able to insert manual IDs”

Yes, without any problem

grazie

**Comment by DavideLicheri** [comment]
> “Reopening the window allowed me to insert my manual IDs”
> 
> I will try
> 

NO CHANCE
with Safari on a Mac M1 with Sonoma

**Comment by goessebr** [comment]
We will review the issue. The manual ID generation strategy introduced in version 2.0.0 is quite inconsistent. When the ID input is enabled, other issues arise.

For reference, performing a hard refresh in Safari is slightly different, but you might have already figured that out:
![image](https://github.com/user-attachments/assets/1b47c18b-c82a-4e43-b26c-b85e41c67412)

**Comment by goessebr** [comment]
Hi @DavideLicheri,
The new atramhasis 2.1.1 is now available with a fix for this issue. It is now possible add your own ID. You might still need a hard browser refresh though.
